### ISSUE TITLE
Symbol's function definition is void

### ISSUE THREAD

**Issue by krzysztof-magosa** [expez/company-quickhelp#10]
I cannot get it working.
It displays below error during initialization.

```
Error in post-command-hook (company-post-command):
(error "Company: Front-end company-quickhelp-frontend error
\"Symbol's function definition is void: pos-tip-hide\" on command hide")
```
- OS X 10.10.2 (Yosemite)
- GNU Emacs 24.4.1
- company-quickhelp  20150322.451
- pos-tip            20150318.813

**Comment by expez** [comment]
`pos-tip-hide` is defined in the `pos-tip` library.  You'll get this error if `pos-tip` isn't being loaded properly. 

Did you enable this mode by some other means than adding`(company-quickhelp-mode 1)` to your `.emacs`?

 Putting `(require 'pos-tip)` somewhere in your `.emacs` is likely to fix this, but that really shouldn't be necessary as the loading of  `company-quickhelp` should trigger the loading of `pos-tip`.

**Comment by krzysztof-magosa** [comment]
I'm loading company-quickhelp using use-package.
I will try to add loading pos-tip before company-quickhelp to check how it's working with that.

**Comment by krzysztof-magosa** [comment]
It's weird because the only function beginning with 'pos' I see in C-x is 'pos-tip-w32-max-width-height'.
I found below declaration in pos-tip.el... So it looks like some problem with loading of pos-tip, but to be honest I have no idea how to debug that.

```
(defalias 'pos-tip-hide 'x-hide-tip
  "Hide pos-tip's tooltip.")
```

**Comment by krzysztof-magosa** [comment]
Correct me if I'm wrong but pos-tip is only for X version of emacs...

**Comment by expez** [comment]
> Correct me if I'm wrong but pos-tip is only for X version of emacs...

This is not the problem.  I'm using `company-quickhelp` on windows right now, where `X` isn't available.  

I've no idea what `use-package` is.  But it's not an emacs built-in.  If you don't want to follow the instructions in the readme, but enable the mode in some other manner, then you're on your own.  See my previous post for suggested solutions.

**Comment by krzysztof-magosa** [comment]
Shortly saying use-package is wrapper ensuring that you have installed specified packages from Melpa and does loading of them. Manual (require 'pos-tip) also doesn't help. It looks that for some reason pos-\* functions are not visible after loading pos-tip. So it looks like problem with pos-tip and not your plugin.

**Comment by expez** [comment]
Is this how you're using `use-package`?

``` elisp
(use-package company-quickhelp
  :ensure t
  :config (company-quickhelp-mode 1))
```

If so, could you, temporarily, try dropping the `use-package` wrapper and just put `(company-quickhelp-mode 1)` in your `.emacs` to see if that fixes the problem?

**Comment by krzysztof-magosa** [comment]
It doesn't help. For unknown reason function 'pos-tip-hide' is not available.
I tried to load manually pos-tip.el but it doesn't help also.
Anyway, we can close this ticket, because it's not strictly related to company-quickhelp, but more with pos-tip.
