### ISSUE TITLE
ESS no documentation available

### ISSUE THREAD

**Issue by safre19** [expez/company-quickhelp#102]
When I try to show documentation in ESS mode, I get "No documentation available".  It works in other mode.

![Screen Shot 2020-06-18 at 2 41 49 PM](https://user-images.githubusercontent.com/56228835/85060950-0bc4f000-b174-11ea-8ef3-62fdb511cf89.png)

**Comment by dgutov** [comment]
What does `M-x company-diag` say?

**Comment by safre19** [comment]
It says :
```
Emacs 26.3 (x86_64-apple-darwin19.0.0) of 2019-11-17 on d12frosted.local
Company 0.9.12

company-backends: (company-capf company-yasnippet)

Used backend: company-yasnippet
Major mode: ess-r-mode
Prefix: ""
Completions:
  #("#!" 0 2 (yas-prefix-offset 0 yas-template #s(yas--template "#!" "#!/usr/bin/env ${1:bash}
```

**Comment by dgutov** [comment]
If only the yasnippet backend is used, you might want to browse ESS's documentation to find out why its completion is not working. And what is needed to turn it on.

**Comment by safre19** [comment]
Ok, I thought that by using ess-use-company it automaticly turned it on.

**Comment by dgutov** [comment]
That would be the question for ESS support.

Perhaps you need to launch an inferior process first, or something like that.

**Comment by dgutov** [comment]
Or perhaps they just don't implement the `doc-buffer` command.

**Comment by safre19** [comment]
Ok I made it work by setting company-backends manually with C-h V to `((company-R-library company-R-args company-R-objects))`. 
The thing is I am still new to emacs and I don't know how to setup company-backends in my config. I tried a lot of suggestions, but none of them worked.

**Comment by dgutov** [comment]
Was there a particular suggestion in ESS's docs that you tried?

**Comment by safre19** [comment]
Solved thanks to [this issue](https://github.com/emacs-ess/ESS/issues/955)! 
This is what I added in my config. 
```
(setq ess-use-company nil)
(after! ess-r-mode
  (set-company-backend! 'ess-r-mode
    '(:separate company-R-library company-R-args company-R-objects)))
```
Thanks for your help!

**Comment by dgutov** [comment]
I was wondering whether their official docs make this clear enough.

Anyway, glad you got this working.
