### ISSUE TITLE
Tooltip xpos offset too wide by 5 chars

### ISSUE THREAD

**Issue by Dr-Dd** [expez/company-quickhelp#106]
The latest patch broke the offset position by 5 characters.

Seems to be about the line number fix #104, maybe it's not needed anymore now that the overlay position logic has been reworked

With the fix:
````elisp
(overlay-position (* (frame-char-width)
                     (+ (- (if ovl (overlay-get ovl 'company-column) 1) 1)
                        (if (bound-and-true-p display-line-numbers)
                            (+ (line-number-display-width) 2) 0))))

````

![4](https://user-images.githubusercontent.com/37450282/85677677-0ada1400-b6c8-11ea-9f9a-c39c0b0b5289.png)

Without the temporary fix:
````elisp
(overlay-position (* (frame-char-width) 
                     (- (if ovl (overlay-get ovl 'company-column) 1) 1)))
````

![good](https://user-images.githubusercontent.com/37450282/85677741-1cbbb700-b6c8-11ea-87e8-fb199c86535a.png)

**Comment by dgutov** [comment]
Thank you for reporting this. I'll have to take a deeper look.

The fix is not so obvious because, when the completions popup is rendered above the current line (the line is at the bottom of the window), the doc popup is positioned correctly.

**Comment by dgutov** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=42039

**Comment by dgutov** [comment]
Should be fixed now. And if anyone's still having problems in the other case I've mentioned above, please upgrade to the latest build of Emacs 27. Or newer.

**Comment by Dr-Dd** [comment]
Great! Thanks
