### ISSUE TITLE
Error running timer ‘company-quickhelp--show’: (wrong-type-argument overlayp nil)

### ISSUE THREAD

**Issue by wyuenho** [expez/company-quickhelp#108]
This seems to show up when there's only one candidate and no company tooltip is showing.

**Comment by wyuenho** [comment]
@dgutov https://github.com/company-mode/company-quickhelp/commit/9a0d860580d5b9359cb0a70ed1fc7bb294bbbaff broke things. Clearly every other variable in the let* bindings makes no assumption for the existence of the overlay but this line does, so it occasionally shows an error.

**Comment by mahito1594** [comment]
I get the same trouble.  I am not very familiar with Emacs Lisp, but I think that it is sufficient to replace [the code at line 192](https://github.com/company-mode/company-quickhelp/blob/c401603685edafa82454fbf045c835e055e8bc56/company-quickhelp.el#L192) with something like

``` elisp
(goto-char (if ovl (min (overlay-start ovl) (point)) (point)))
```

**Comment by wyuenho** [comment]
Since there's a check for the existence of ovl and doc below, that whole block of variables can be moved inside instead of adding unnecessary checks for ovl all over the place.

**Comment by dgutov** [comment]
Thanks for the report and the patch!
