### ISSUE TITLE
First doc popup takes too long to show

### ISSUE THREAD

**Issue by alexander-yakushev** [expez/company-quickhelp#11]
So as I'm typing something in a Clojure buffer, company's completion box appears. After ~3.5 seconds (delay is consistent, I measure it a few times) a help window shows up. If I then start switching between completion candidates, the delay before help appears is the expected 0.5 seconds. Any ideas where the initial delay comes from?

Env: the very latest CIDER, cider-nrepl, company and company-quickhelp.

**Comment by expez** [comment]
I just updated everything myself and I'm not seeing such a long delay before the documentation popup appears.  I've only tested in the repl because `cider-doc` doesn't work in regular clj buffers atm.

**Comment by alexander-yakushev** [comment]
Hmm... It does for me :) And you a right, in the REPL there is no delay. Also, in the clojure buffers if completion is initiated manually (via `company-complete`) there is also no delay. It happens only during automatic as-you-type completion.

**Comment by expez** [comment]
If you debug `company-quickhelp-frontend` when is it called?  

If it's called 3s into the 3.5s then there's little I can do other than suggest that you move the frontend to the front of the `company-frontends` list (it's at the back now) and hope that makes a difference.

**Comment by expez** [comment]
@alexander-yakushev ping

**Comment by alexander-yakushev** [comment]
How do I debug it?

**Comment by expez** [comment]
`M-x find-library <RET> company-quickhelp <RET>` will take you to the source code of `company-quickhelp`. Then navigate to `company-quickhelp-frontend` and with point inside the function do `M-x edebug-defun <RET>`.  If you now type say `(set` company-quickhelp will set a timer and after `company-quickhelp-delay` seconds you should enter `company-quickhelp-frontend` in the debugger.  

To disable instrumentation just do `eval-defun` to re-evaluate the function without any instrumentation.

If you have the time, [edebug](http://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html) is very powerful and quite easy to learn.  You can learn everything you need in 5-10 minutes.

**Comment by alexander-yakushev** [comment]
Can you explain the `(set` part again?

I instrumented `company-quickhelp-frontend` function, and now I'm dropped into the debugger quite often (even if I don't do anything). As I type some expression in a Clojure buffer, frontend function is immediately called (no company window yet), then company appears and `frontend` is called again, a few times. After I step through them all, just company window remains. Quickhelp window does not appear at all while I'm in the debugging mode.

**Comment by expez** [comment]
Suppose the last post was a bit confusing.  It was a copy-paste job from another issue.  In any event we found out what we needed to know: the `company-quickhelp-frontend` is called immediately.

The next thing that happens is that `company--quickhelp-show` is put on a timer and after `company--quickhelp-delay` starts the work of finding the docstring for the selected candidate.  I have positively no idea why it would take longer to get a docstring in a regular clojure buffer than in the repl.

If you have time, you can try to instrument some more stuff and see what happens, perhaps comparing the results with what happens in the repl buffer (where the problem doesn't appear).

**Comment by alexander-yakushev** [comment]
Like I said before, it's not only Clojure buffer that matters, but also that completion is automatic. When I call completion manually from a Clojure buffer, the delay is 0.5sec as expected.

**Comment by expez** [comment]
Is this still a problem @alexander-yakushev, did you investigate further?

**Comment by alexander-yakushev** [comment]
To be honest, I switched back to ac-cider for now. Fuzzy matching is too important for me to give up. I guess it makes sense to close the issue for now, as it is quite weird and company-quickhelp doesn't seem to be responsible for it.
