### ISSUE TITLE
Maintain terminal support.

### ISSUE THREAD

**Issue by jcs090218** [expez/company-quickhelp#111]
Hi `company-mode` team, 

I have followed this thread https://github.com/company-mode/company-quickhelp/pull/94. And wanting to ask if there is no one willing to support this package with terminal support; I am willing to support it because I personally use Emacs inside terminal and this package is great package is very important to me while using it with `company-mode`.

And I also would like to ask, does this package planning on to move toward to elpa? Base on my previous PR here https://github.com/company-mode/company-quickhelp/pull/100, I uses `popup.el` to implement terminal support. And this might be an issue...

Let me know what you guys think! Thanks! 👍

**Comment by dgutov** [comment]
By "maintain", you mean "add", right?

I'd be happy with terminal support, but unfortunately I really don't want to increase the number of packages that rely on `popup.el`: its authors have always been a fairly closed group, and they deliberately chose not to contribute to GNU ELPA.

Someday, someone hopefully will create a alternative package (perhaps based on company's overlay code), and I'll happily incorporate it here. It's not a trivial task, unfortunately, so it's pretty low on my list. Sorry.

Regarding whether this can end up in GNU ELPA, I don't know yet, but I'd like to keep the option open.

**Comment by jcs090218** [comment]
> By "maintain", you mean "add", right?

I think yes!

> I'd be happy with terminal support, but unfortunately I really don't want to increase the number of packages that rely on popup.el: its authors have always been a fairly closed group, and they deliberately chose not to contribute to GNU ELPA.
>
> Someday, someone hopefully will create a alternative package (perhaps based on company's overlay code), and I'll happily incorporate it here. It's not a trivial task, unfortunately, so it's pretty low on my list. Sorry.

> Regarding whether this can end up in GNU ELPA, I don't know yet, but I'd like to keep the option open.

I agree with you here! Thanks for me letting me know! I appreciated! 👍
