### ISSUE TITLE
Support display using `eldoc-box`

### ISSUE THREAD

**Issue by FelipeLema** [expez/company-quickhelp#112]
Hey, there

I'm liking this package a lot, although I would like to unify my help displays to a single instance.

Right now I'm using [`eldoc-box`](https://github.com/casouri/eldoc-box/) to display help on a separate frame and company-quickhelp for completion. When I get `company` to start a completion I get help from both `company` and "whatever-I-was-looking-at-in-the-code" through `eldoc-box`.

I'd like to have `company-quickhelp` to take ownership of `eldoc-box`. This way I would only have a single unified frame displaying help.

Thanks for the effort so far, everyone.

**Comment by dgutov** [comment]
I'm not really sure it's possible from this end.

Perhaps you could ask for such integration in the `eldoc-box` project? It would serve as a replacement for this mode.

**Comment by FelipeLema** [comment]
Closing as "not possible". Thanks for answering.
