### ISSUE TITLE
Question: Which face is this?

### ISSUE THREAD

**Issue by ig-perez** [expez/company-quickhelp#116]
Hi, thanks for making this package! ... I want to reduce the font size of the documentation shown in the right side of the dropdown list, but I'm not able to find the face name. (I'm using `list-faces-display`) Can you help me please?

![image](https://user-images.githubusercontent.com/33359427/103485994-867bf280-4dc8-11eb-9a70-0651fb4474d7.png)

As you can see I successfully reduced the font size of the dropdown list items by customizing the `tolltip` face, but it didn't affect the documentation part, so I assume it is a different face..

Thanks!

**Comment by dgutov** [comment]
Hi!

You seem to be using `company-box`. I think it has its own doc popup: https://github.com/sebastiencs/company-box/blob/master/company-box-doc.el

**Comment by ig-perez** [comment]
Thanks @dgutov ! It seems the dropdown list of candidates and the documentation box faces of `company-box` overrides the ones defined in `company`. I changed the font size like this:

```emacs-lisp
(use-package company-box
  :after company
  :ensure t
  :hook (company-mode . company-box-mode)
  :config
  (setq company-box-show-single-candidate t)
  (setq x-gtk-resize-child-frames 'hide)  ;; This solves the variable scrollbar width. This is probably related to Wayland

  (add-to-list
   'company-box-frame-parameters
   '(font . "JetBrains Mono-11")
   )
  )
```
I don't like setting the font like that, I guess it is better to set a fixed face and inherit from it, but, I guess it is not possible in that case (not an Lisp expert)

Anyway, everything is as I like now.
