### ISSUE TITLE
Company-quickhelp eats newlines

### ISSUE THREAD

**Issue by andreyorst** [expez/company-quickhelp#119]
Here's how company-quickhelp displays the documentation:

![image](https://user-images.githubusercontent.com/19470159/118359748-a2b94880-b58d-11eb-9a6c-84df7d88169a.png)

And here's how company-box displays it:

![image](https://user-images.githubusercontent.com/19470159/118359796-caa8ac00-b58d-11eb-9938-c74a1c0a28cd.png)

Here's how LSP-UI displays the same doc:

![image](https://user-images.githubusercontent.com/19470159/118359840-f6c42d00-b58d-11eb-9850-57293860fa03.png)

Here's a documentation from CIDER in company-box:

![image](https://user-images.githubusercontent.com/19470159/118359924-2b37e900-b58e-11eb-8045-417aaf94efba.png)

And here it again in company-quickhelp:

![image](https://user-images.githubusercontent.com/19470159/118360110-db0d5680-b58e-11eb-8432-5eca8d4ad160.png)

Given that two different sources render identically in company-box and LSP-UI, and have no newlines in first lines in company-quickhelp, I guess this is a company quinkhelp issue.

**Comment by dgutov** [comment]
Thanks for the report.

How does the corresponding `M-x company-show-doc-buffer` buffer look? It's bound to `C-h` by default when the popup is open.

**Comment by andreyorst** [comment]
It looks normally:

![image](https://user-images.githubusercontent.com/19470159/118375680-edf24c00-b5cb-11eb-9940-2591b5c43470.png)

Here's the same doc in the popup:

![image](https://user-images.githubusercontent.com/19470159/118375707-15491900-b5cc-11eb-841b-8d6665211691.png)

**Comment by dgutov** [comment]
All right. Could you save it to a file from that buffer and paste here?

It would be in some invisible buffer, but it shouldn't be too hard to hunt down.

**Comment by andreyorst** [comment]
sorry, do you mean from the `*company-documentation*` buffer?

**Comment by andreyorst** [comment]
Here's the contents of the ` *tip*` buffer:

```
clojure.core/persistent!  [coll] ---- Returns a new, persistent version of the
transient collection, in constant time. The transient collection cannot be used
after this call, any such use will throw an exception.

----
/home/andreyorst/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar:clojure/core.clj
```

Here's the `*company-documentation*` buffer contents:

```
clojure.core/persistent!
[coll]
----
Returns a new, persistent version of the transient collection, in
constant time. The transient collection cannot be used after this
call, any such use will throw an exception.

----
/home/andreyorst/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar:clojure/core.clj
```

Both as files (saved directly from respecing buffers with `C-x C-w`):
[*company-documentation*.txt](https://github.com/company-mode/company-quickhelp/files/6488103/company-documentation.txt)
[*tip*.txt](https://github.com/company-mode/company-quickhelp/files/6488104/tip.txt)

**Comment by dgutov** [comment]
Thanks.

Apparently it's due to an effort to "reflow" documentation buffers that are too wide, from https://github.com/company-mode/company-quickhelp/pull/54/commits/5b624bf38c46b3e3ea5a517283dcf7c7091bbbe8. But that seems impossible to do without side-effects like this.

**Comment by dgutov** [comment]
I've pushed a simple patch, please test.

**Comment by andreyorst** [comment]
seems to work now! Thanks!
