### ISSUE TITLE
Quickhelp content showing as part of the completition candidate

### ISSUE THREAD

**Issue by jjnilton** [expez/company-quickhelp#121]
When using lsp-mode, the signature help content shows inside the completion candidate instead of a separate frame. It also only shows after I move between candidates:

![](https://media.discordapp.net/attachments/789890622424219658/950008156929548348/Peek_2022-03-05_22-58.gif)

**Comment by dgutov** [comment]
Hi!

Please report this to `lsp-mode`. The second part especially looks like a bug.

**Comment by jjnilton** [comment]
I opened a discussion there https://github.com/emacs-lsp/lsp-mode/discussions/3386 - but maybe an issue would be better. I was suggested to ask here, because it seems it should work out of the box.

**Comment by dgutov** [comment]
I just pointed out a problematic behavior which certainly looks like a bug.

Now that you clarified, you also seem to be asking for a different feature than what this package provides. But IIRC lsp-mode does have its own feature for showing the signature help using posframe: https://github.com/emacs-lsp/lsp-mode/pull/1999

I haven't been able to quickly locate the docs for it, though.
