### ISSUE TITLE
Docs appear in minibuffer on hovering keyword

### ISSUE THREAD

**Issue by rob137** [expez/company-quickhelp#122]
I'm using company-quickhelp with lsp-mode, seeing strange behavior in CSS and HTML files.  Typescript / JavaScript are behaving normally.

The quickhelp popup does not appear during autocompletion:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/18082006/184251158-a434b451-d6a6-4c17-adff-b02015adc20d.png">

However the docs appear in the minibuffer when the point is placed over a key word:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/18082006/184251116-0c9e2e72-45c7-49d2-aeb3-aebe9358c27b.png">

**Comment by dgutov** [comment]
Could you file that against lsp-mode first? Or maybe start by asking at their Discord.
