### ISSUE TITLE
Company showing blank popups

### ISSUE THREAD

**Issue by FiV0** [expez/company-quickhelp#124]
Hi,

I am having blank popups. I know there is a previous issue similar to this https://github.com/company-mode/company-quickhelp/issues/90, but the solution proposed there didn't work for me. 
![Selection_035](https://user-images.githubusercontent.com/23086133/199224347-1d499200-eb18-4e3e-bd7a-c8c9e9ff3887.png)

My company backends look like this:
```elisp
ELISP> company-backends
(company-terraform company-bbdb company-semantic company-cmake company-capf company-clang company-files
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   company-oddmuse company-dabbrev)
```
Let me know if anything else would be helpful debugging this.

**Comment by dgutov** [comment]
Is there any chance that the backend reports empty strings there?
