### ISSUE TITLE
docstring for company-quickhelp-delay needs small fix?

### ISSUE THREAD

**Issue by mandarm** [expez/company-quickhelp#127]
Currently says:

`If set to nil the popup won’t automatically appear, but can still be triggered manually using ‘company-quickhelp-show’.`

There's only `company-quickhelp--show`, a non-interactive function. As far as I can tell, this should probably be:

`If set to nil the popup won’t automatically appear, but can still be triggered manually using ‘company-quickhelp-manual-begin’.`

**Comment by dgutov** [comment]
Indeed. Thanks for the report!
