### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by aguynamedben** [expez/company-quickhelp#128]
I'm comparing different doc preview modes and am curious if company-quickhelp can provide better formatting and syntax highlighting similar to eldoc-box.

### company-quickhelp
No syntax highlighting, no horizontal rule
<img width="789" alt="image" src="https://github.com/company-mode/company-quickhelp/assets/107841/7e9b7885-c00a-457d-83fb-9b0e7af56552">

### stock eldoc buffer
Nice syntax highlighting, horizontal rule, but some goofy &nbsp;'s left (from Markdown?)
<img width="851" alt="image" src="https://github.com/company-mode/company-quickhelp/assets/107841/20234fcd-97c6-44eb-be1a-94bcc3e7d130">

### eldoc-box
Nice syntax highlighting, horizontal rule, but doesn't integrate with candidates for company, corfu, etc. Note the eldoc-box readme says they do some "pretty" preprocessing, maybe some code can be shared from that?
<img width="602" alt="image" src="https://github.com/company-mode/company-quickhelp/assets/107841/b88ea120-3926-482d-9dbb-bb5c6bd1d03a">

### corfu-popupinfo-mode
About the same as company-quickhelp, but monospace font.

Are there any plans to improve the formatting for company-quickhelp?

**Comment by aguynamedben** [comment]
I'm going to close this. I think most of this nastiness was coming from PyRight language server, which seems to give back "nasty Python docstrings via plaintext" as its documentation at point.

I installed pylsp (https://github.com/python-lsp/python-lsp-server) and it's giving proper Markdown and it looks much better. Interestingly, Eglot has a feature where if you have markdown-mode installed, Eglot will use markdown-mode to clean up Markdown from the language server. But PyRight was giving back "plaintext" and it was all Python docstrings, that's why it looks so plain in company-quickhelp.

**Comment by dgutov** [comment]
Indeed, it sounds like eldoc and documentation buffer use different sources of information, which had different degrees of formatting applied by the first LSP server that you used.

In general, it's hard for me to say whether PyRight is misbehaving, or if this is a variant of the norm. It would be a better question for the developers of lsp-mode or eglot (whichever you are using), since those as adaptors in both cases, transforming the data.
