### ISSUE TITLE
Can this package support Python quick help?

### ISSUE THREAD

**Issue by suzzvv** [expez/company-quickhelp#14]

**Comment by expez** [comment]
Yes. All this package does is display documentation in a popup, so in that manner it is language agnostic.  If the completion backend provides documentation it will be shown automatically.  

I don't write python myself but afaik there are several potential backends to choose from like `company-jedi` and whatever ships with `elpy`.

**Comment by suzzvv** [comment]
It works for Elisp-mode just as I expected. However when I use `company-jedi`, it didn't work. Any ideas? Thanks.

**Comment by expez** [comment]
[emacs-company-jedi](https://github.com/syohex/emacs-company-jedi/blob/master/company-jedi.el#L105) doesn't appear to provide any documentation.  What I previously thought of as `company-jedi` seems to have been renamed to `anaconda` and there's now both [company-anaconda](https://github.com/proofit404/company-anaconda/blob/master/company-anaconda.el) and [anaconda-mode](https://github.com/proofit404/anaconda-mode).  

The last time I did any python coding I used [elpy](https://github.com/jorgenschaefer/elpy) which also provides the ability to lookup documentation.

**Comment by suzzvv** [comment]
Thanks anyway, I will try that.
