### ISSUE TITLE
Window system frame should be used

### ISSUE THREAD

**Issue by tayoto** [expez/company-quickhelp#15]
hi, 
this is my Backtrace when i use quickhelp

Debugger entered--Lisp error: (error "Window system frame should be used")
  x-display-pixel-width(#<frame F1 0x102019f00>)
  pos-tip-x-display-width(#<frame F1 0x102019f00>)
  pos-tip-show("abort() -> does not return!\n\nAbort the interpreter immediately.  This 'dumps core' or otherwise fails\nin the hardest way possible on the hosting operating system$
  company-quickhelp--show()
  apply(company-quickhelp--show nil)
  byte-code("r\301^H\302H^H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 nil company-quickhelp--show nil idle 0])

I have no idea why

**Comment by expez** [comment]
Hi

Can you do `C-h v window-system <RET>` and let me know what the value of the variable `window-system` is?

**Comment by tayoto** [comment]
sorry for delay response, because i'am from china, and the different time zone 

this is the value of window-system value:

window-system is a variable defined in `C source code'.
Its value is nil
It is a terminal-local variable; global value is the same.

Documentation:
Name of window system through which the selected frame is displayed.
The value is a symbol:
 nil for a termcap frame (a character-only terminal),
 'x' for an Emacs frame that is really an X window,
 'w32' for an Emacs frame that is a window on MS-Windows display,
 'ns' for an Emacs frame on a GNUstep or Macintosh Cocoa display,
 'pc' for a direct-write MS-DOS frame.

**Comment by expez** [comment]
Right, that's the problem.  `company-quickhelp` doesn't work in the terminal.

**Comment by tayoto** [comment]
When I use auto-complete which uses popup, it's ok. 
So, is this the feature of pos-tip which is used by company-quick-help?

**Comment by expez** [comment]
yes, `pos-tip` only works for GUI emacs and not in the terminal. `popup` is incredibly buggy so the use of `pos-tip` is intentional.

When I have some time I'll put a check in place so the next time someone tries to run company-quickhelp in the terminal a friendly error message is displayed instead of a stacktrace.

Sorry I couldn't give you the answer you wanted.

**Comment by tayoto** [comment]
thank you

**Comment by Xe** [comment]
I just ran into this

**Comment by expez** [comment]
@Xe You got an unfriendly explosion instead of a helpful error message?

**Comment by Xe** [comment]
Yep, i'm kind of annoyed that this doesn't work in the terminal, a lot of my workflow involves running emacs persistently on a remote server and ssh-ing into it.

**Comment by expez** [comment]
What was the error message you got?  I'd really appreciate it if you did `M-x toggle-debug-on-error` and pasted the entire stacktrace you get when reproducing the problem.
