### ISSUE TITLE
freezes the startup of emacs daemon

### ISSUE THREAD

**Issue by shackra** [expez/company-quickhelp#16]
I have installed company-quickhelp version `20150611.2305` from Melpa with these dependencies:
- company-0.8.9
- pos-tip-0.4.6

I started experiencing a weird bug today, the initialization of emacs daemon was freeze exactly on the line `(company-quickhelp-mode 1)` in my Emacs configuration. I've been using company-quickhelp for about two weeks or so but this is the first time it presents a critical issue like this one.

Starting a non-daemon session of emacs don't get freeze during initialization.

**Comment by expez** [comment]
Which os and version of emacs are you running?

**Comment by elzorrorebelde** [comment]
GNU Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 3.16.2) of 2015-04-20 on sammy

uname -a: Linux abril.charola 4.0.4-gnu-rt1-2-rt #1 SMP PREEMPT RT Thu Jun 11 04:42:27 UYT 2015 i686 GNU/Linux

Lars Andersen writes:

> Which os and version of emacs are you running?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/expez/company-quickhelp/issues/16#issuecomment-111686180

## 

Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by expez** [comment]
Pretty sure this is the problem.  I'd test it myself but `--daemon` stopped working on arch linux in version 24.5.

`melpa` builds recipes every hour, I think, so this should be available soon.  Let me know if this doesn't solve the problem.

**Comment by elzorrorebelde** [comment]
fixed, thank you!
