### ISSUE TITLE
Position of help popup overlaps or hides company popup

### ISSUE THREAD

**Issue by swarnendubiswas** [expez/company-quickhelp#18]
Position of company quickhelp pop has started overlapping and hiding the company popup. Typing more characters becomes difficult because one cannot see. I am on GNU Emacs 24.5.

I did not observe this issue earlier, although I had quickhelp enabled. Maybe some recent change caused this?

![screenshot from 2015-07-03 22-57-50](https://cloud.githubusercontent.com/assets/7343807/8506203/3b281570-21d7-11e5-9d3a-5c077b0fb874.png)

**Comment by expez** [comment]
If you look at the master branch there hasn't been any significant changes for quite some time.  Only stuff like better error messages.

If you don't load any of your own configuration, e.g. by starting emacs with `emacs -q` and only load `company-mode` and `company-quickhelp` does this still happen?

**Comment by swarnendubiswas** [comment]
I get what you are saying. I stripped of my init files to bare minimum, and the problem still persists. 

I started emacs -Q, and loaded the two modes with load-file. However, I can't seem to get company-quickhelp popup to appear itself.

**Comment by expez** [comment]
I cloned your emacs configuration in an attempt to reproduce the problem but everything worked as expected.

Without being able to reproduce the problem there's unfortunately very little I can do.

If you want to use this as an opportunity to dive into emacs debugging I'd be happy to help you solve your own problem :) 

ps. I had to manually add `melpa` as an archive to bootstrap your `dotemacs`. It seems it couldn't find `use-package` without doing that.

**Comment by swarnendubiswas** [comment]
Thanks for your time. Should be one of my own configuration niggles. Would love to learn a bit more about debugging emacs.

**Comment by expez** [comment]
`M-x find-library <RET> company-quickhelp <RET>` will take you to the source code of `company-quickhelp`. Then navigate to `company-quickhelp--show` and with point inside the function do `M-x edebug-defun <RET>`.  

If you now start typing something that will trigger a documentation popup, preferably in another buffer, you should enter `company-quickhelp--show` in the debugger.  At that point you'll have to step through the function, and possible other functions to looks for anything suspicious.

To disable instrumentation just do `eval-defun` to re-evaluate the function without any instrumentation.

If you have the time, [edebug](http://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html) is very powerful and quite easy to learn.  You can learn everything you need in 5-10 minutes.

**Comment by ardpp** [comment]
I have the same issue, even with `emacs -Q` using Emacs 25.0.50.1
I can not tell when this started though.

**Comment by failable** [comment]
Same here on GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-11 on builder10-9.porkrind.org

**Comment by expez** [comment]
There's now a pull-request available to fix this issue.  I'm testing it now for regressions, but it would be great if some one you had time to verify the fix.

**Comment by ardpp** [comment]
Just had a quick look. When editing elisp files this fix seems to work ok, though I would prefer the help-window to stay inside the emacs frame which is not always the case. 

In python files (using elpy) I get the following error instead of a quickhelp-window

```
Error running timer `company-quickhelp--show': (wrong-type-argument overlayp nil)
```

Let me know if I can provide more information.

**Comment by spirani** [comment]
@ardpp 
I started getting that same error. This is what fixed it for me: https://github.com/spirani/company-quickhelp/commit/1d2a8cdffc275f123b30a9990e48cdef9ede81d2

Could you take a look at this and see if it fixes the problem?

**Comment by ardpp** [comment]
@spirani 
Yes, it works as expected now!

**Comment by swarnendubiswas** [comment]
@expez  @spirani Yes, seems to work for me as well.
