### ISSUE TITLE
Help (mostly) not showing in Clojure buffer

### ISSUE THREAD

**Issue by asampal** [expez/company-quickhelp#20]
I've got the quickhelp popup working fine in the cider-repl buffer. In Clojure buffers, on the other hand, I only get the help popup for 'def', no other text triggers it. I get the company completion popup as expected, for any valid prefixes, but as I move over the candidates, no help is shown - except it is for 'def'. 

I'm on Windows 8.1 64 bit, Emacs 24.5.1

**Comment by asampal** [comment]
I should add that invoking C-h on a candidate in the completion popup which doesn't bring up quickhelp shows "No documentation available" in the mini buffer. So how is it that there is one prefix, 'def' which does have help, but anything else doesn't?

**Comment by expez** [comment]
Hi

I ask company for the documentation, so if <kbd>C-h</kbd> doesn't return any documentation, then I have nothing to display in the popup.

Are you using [CIDER](https://github.com/clojure-emacs/cider)?  Without CIDER, and its middleware installed, company doesn't have a good backend to provide it with completion candidates or documentation.  This might be why the performance of <kbd>C-h</kbd> is lackluster.

**Comment by asampal** [comment]
Yes, I am using Cider. Maybe I wasn't being clear enough in the initial comment when I mentioned that I get proper help in the _cider-repl_ buffer (the repl created as a result of 'cider-jack-in'). Also, in the Clojure buffer, the help that does show for the 'def' prefix is a full help string that isn't available without Cider. Again, the list of candidates shown by company in the Clojure buffer is the full one (with annotations, etc) as provided by Cider - it's just the help that is missing.

**Comment by expez** [comment]
If you don't see docstrings, for vars which have docstrings, when you hit <kbd>C-h</kbd> on a company candidate, you should file a bug with company or with CIDER.  All company-quickhelp does it display that docstring in a popup.  If there isn't one, there's unfortunately nothing I can do.

**Comment by asampal** [comment]
OK, I will. I assume you're saying that the problem is in cider-nrepl rather than Cider specifically, which I assume company-quickhelp is using to talk to Cider, right?

**Comment by expez** [comment]
company-quickhelp knows nothing about CIDER.  It only asks company for the documentation you get when you hit <kbd>C-h</kbd> on a completion candidate in the company popup.  This is why company-quickhelp works, without my doing anything at all, for any company backend which provides documentation :)

**Comment by asampal** [comment]
It's not clear to me if the issue should be reported to company or to cider-nrepl. I guess I will report it to the first in the chain, which would be company.

**Comment by asampal** [comment]
Closing since this is just due to not loading the buffer before attempting to get the help popups.
