### ISSUE TITLE
[feature request] make company-quickhelp popup doc manually.

### ISSUE THREAD

**Issue by stardiviner** [expez/company-quickhelp#22]
company-quickhelp make navigation in company popup menu slow. I hope company-quickhelp doc popup can be triggered manually through a function keybinding.
Like this:

``` lisp
(setq company-quickhelp-delay 0.3) ; TODO: set to `nil' to trigger popup doc manually.
(define-key company-active-map (kbd "<f1>") 'company-show-doc-buffer)
(if (functionp 'company-quickhelp--show)
    ;; (define-key company-active-map (kbd "M-h") 'company-quickhelp--show)
    (define-key company-active-map (kbd "M-h") 'company-quickhelp--show)
  (define-key company-active-map (kbd "M-h") 'company-show-doc-buffer)
  )
```

**Comment by expez** [comment]
I'd love it if you tried this out, to make sure it satisfies your needs, before I tag the new release for melpa-stable.

**Comment by stardiviner** [comment]
@expez This works great, and faster then auto popup. very awesome. Thanks.
