### ISSUE TITLE
work for Cask projects

### ISSUE THREAD

**Issue by fommil** [expez/company-quickhelp#23]
This is a really nice feature, thank you!

In `emacs-lisp-mode` (I don't know what else you support) I noticed that it only works for items that have been loaded into the REPL. It would be good if it also worked for projects as defined by `Cask` definitions, in much the way that flycheck is able to check a project based on the Cask definition.

**Comment by expez** [comment]
> I don't know what else you support

Anything that has a doc when you hit <kbd>F1</kbd> using `company`. 

 I don't know how company gets its candidates for elisp, but you're right in that it probably cannot know about stuff that hasn't been loaded yet.  Anyway, all this project does is redisplay available documentation in a popup, if no documentation (or completion candidates) are available there's nothing I can do.

**Comment by fommil** [comment]
oh sweet, then close as invalid because this is about populating company. We should definitely try to provide docs for `ensime-company` in that case.

**Comment by expez** [comment]
> We should definitely try to provide docs for ensime-company in that case.

This should be pretty easy and your users will love you for it!

**Comment by fommil** [comment]
hah, easy for you to say. The docs are quite difficult to get hold of, but we're halfway there.

**Comment by expez** [comment]
> hah, easy for you to say. The docs are quite difficult to get hold of, but we're halfway there.

Ah, I only meant that the company related code is easy to write.
