### ISSUE TITLE
Does this work in emacs -nw mode?

### ISSUE THREAD

**Issue by ahungry** [expez/company-quickhelp#24]
Does this work in emacs -nw or the GUI only?

**Comment by expez** [comment]
GUI only.  This is a limitation of `pos-tip`, the library responsible for creating the popups.  Other alternatives exist, which work in both environments, but they are terribly buggy.  There's some talk of bundling a popup lib into emacs itself for version 25 and if that's the case it's likely to support both environments in a satisfying manner and I'll likely upgrade.

**Comment by RasmusWL** [comment]
I would also like to have this work without GUI. How about an option to display in the message area?

**Comment by expez** [comment]
Just use another library if you don't like GUI emacs.  

I prefer libraries which does one thing and does it well so this is never going to happen.

**Comment by ahungry** [comment]
Only works in GUI and not terminal?  I guess that's why they call it a pos-tip (/kidding)

**Comment by ahungry** [comment]
Came back around to this after some time: https://github.com/ahungry/company-quickhelp

**Comment by NightMachinery** [comment]
@expez Did that builtin tooltip API materialize?

**Comment by dgutov** [comment]
Not so far.

Extracting Company's overlay popup renderer to a lib seems like the best bet for the near future.
