### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by vjohansen** [expez/company-quickhelp#25]
"GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570"
Windows 7

It slows down most company operations. It hangs all the time for  a few seconds.

Tested with elpy-mode (a python) mode  and emacs-lisp-mode

profiler-report

```
- timer-event-handler                                             966  92%
 - byte-code                                                      966  92%
  - apply                                                         966  92%
   - company-quickhelp--show                                      965  92%
    - pos-tip-show                                                962  91%
     - pos-tip-show-no-propertize                                 962  91%
      - x-show-tip                                                950  90%
       - face-set-after-frame-default                             629  60%
        - byte-code                                               629  60%
         - face-spec-recalc                                       627  59%
          + face-spec-set-2                                       309  29%
          - make-face-x-resource-internal                         302  28%
           - set-face-attributes-from-resources                   300  28%
            - set-face-attribute-from-resource                    297  28%
             + face-name                                           26   2%
          + face-spec-reset-face                                   12   1%
            face-spec-choose                                        1   0%
       - frame-set-background-mode                                320  30%
        - face-spec-recalc                                        308  29%
         - make-face-x-resource-internal                          290  27%
          - set-face-attributes-from-resources                    287  27%
           - set-face-attribute-from-resource                     284  27%
            - face-name                                            14   1%
             + check-face                                          13   1%
         + face-spec-reset-face                                    16   1%
         + face-spec-set-2                                          1   0%
           face-spec-choose                                         1   0%
        + face-attr-match-p                                        12   1%
      + pos-tip-compute-pixel-position                              3   0%
    + company-quickhelp--doc                                        3   0%
   + company-idle-begin                                             1   0%
+ ...                                                              68   6%
+ command-execute                                                  12   1%
  tooltip-hide                                                      2   0%
```

**Comment by expez** [comment]
> It slows down most company operations. It hangs all the time for a few seconds.

This is definitely not normal and not something I've ever experienced, or had reported before.  I'm writing this message on the lowliest of craptops, so this isn't a hardware problem.  Furthermore, I use this package with windows 7, at some client sites, so that isn't the cause either.

I first suspected this might be a problem with elpy, but if you experience the problem in elisp too, then it's clearly not that.

I'm afraid you'll have to investigate this on your own, because without being able to reproduce the problem it's difficult to find the cause.

**Comment by stardiviner** [comment]
It's slow here too. Not very slow. about 3 seconds.

**Comment by expez** [comment]
> It's slow here too. Not very slow. about 3 seconds.

Do you mean it takes 3 seconds for the popup to appear?  You can reduce `company-quickhelp-delay` (it's default is 0.5s), but once that value approaches 0 there's nothing more I can do.  At that point the action is queued and it's a matter of when emacs gets to it.

I think @vjohansen is experiencing another issue, where this package is causing his entire emacs to become unresponsive and sluggish.  If you're experiencing the same, @stardiviner, I'd love some more details.

**Comment by stardiviner** [comment]
I'm testing, reduce `company-quickhelp-delay` does not help lot. I'm bisecting my mass init files. It will take some time. I will update result after I finished. Thanks for quick response. I think you're right, my slow is different with UP.

**Comment by stardiviner** [comment]
After bisect some mainly relatived init files like company-mode, popup, showtip, color-theme, emacs appearance init files. I found customize face of company-mode and solarized color-theme make company-quickhelp-mode a little slow. (This sounds weird. I know, I will dig deeper)

**Comment by stardiviner** [comment]
I know why now, Emacs slows because load to much things. and don't know why, color-theme-solarized did slow about 1 second delay. I think it's hard to find out why now. I give up.
Summary, not company-quickhelp-mode issue, my emacs config slows popup.

**Comment by vjohansen** [comment]
The slowness happened only when using company-mode. For example when pressing cursor down to move to next candidate.

I can no longer reproduce it. Yesterday my machine rebooted due to Windows updates  and some new elpa/melpa packages probably came in use.

**Comment by expez** [comment]
Aight.  Feel free to re-open if you see this again, @vjohansen.
