### ISSUE TITLE
Replace pos-tip by popup

### ISSUE THREAD

**Issue by csantosb** [expez/company-quickhelp#26]
Any chance to see this replacement ? When using emacs 25, pos-tip is a pain.

**Comment by expez** [comment]
> Any chance to see this replacement ?

No. `popup.el` is quite glitchy and was one of the reasons I switched from `auto-complete` to `company` in the first place.

> When using emacs 25, pos-tip is a pain.

What happens on 25?

**Comment by csantosb** [comment]
> What happens on 25?

Well, just

```
(pos-tip-show "foo bar")
```

gives 

```
Undefined color "color-230"
```

or even

```
wrong-type-argument number-or-marker-p nil
```

errors. I just noticed that other packages I use perform fine with `popup`.

**Comment by expez** [comment]
There is another bug report for emacs 25 in this repo too.  Once 25 is released, and the API is stable, I'll investigate potential solutions.

**Comment by csantosb** [comment]
ok, thanks.
