### ISSUE TITLE
Suggestion: bind company-quickhelp-manual-begin to company-active-map

### ISSUE THREAD

**Issue by xiongtx** [expez/company-quickhelp#27]
First, let me say that I'm really glad I stumbled upon this package, because documentation pop-ups were the one thing I missed from `auto-complete`!

I've got a suggestion: bind the `company-quickhelp-manual-begin` command to `company-active-map` instead of `company-quickhelp-mode-map`. This way, the binding only applies when we are selecting `company` candidates, not all the time.

**Comment by stardiviner** [comment]
You can setup it in your own config file.

**Comment by stardiviner** [comment]
I agree on your opinion.

**Comment by xiongtx** [comment]
Yes, I have set it up in my init file, and it works just fine.

**Comment by expez** [comment]
This is a great idea.  After you opened this issue I added this to my own config, but after thinking some more about this, that's where I think it belongs.  I don't want to modify a keymap I don't own.

**Comment by xiongtx** [comment]
That's fine, but can you make a note of this in the README? 

Binding `company-quickhelp-menu-begin` is to a key in `company-active-map` should be the recommended practice, even if it is not default. Many other packages do something similar by recommending, for example, that a key be bound to `C-c a` even though the default binding is `C-x c a`, since `C-c [a-z]` keys are meant exclusively for the user.

**Comment by expez** [comment]
Sure, done :)
