### ISSUE TITLE
company-quickhelp hijacks existing help buffers

### ISSUE THREAD

**Issue by cpitclaudel** [expez/company-quickhelp#31]
To reproduce:
- Open a help buffer with C-h f
- In the _scratch_ buffer, start typing. Navigating candidates will update the contents of the help buffer in addition to displaying the quickhelp pos-tip.

**Comment by expez** [comment]
I don't think there's any way to fix this.  When company is asked to provide docs it does so by updating the contents of the help buffer as far as I can tell. For elisp this is `*Help*` for clojure it's `*cider-doc*`.

I suppose this problem could be fixed by your suggested docstring backend.

**Comment by cpitclaudel** [comment]
Got it. Indeed, the doc-string thing could work :)
