### ISSUE TITLE
Company Quickhelp and Alchemist

### ISSUE THREAD

**Issue by houli** [expez/company-quickhelp#33]
When using company quickhelp and Alchemist (Elixir completion server) often Emacs will hang and use 100% CPU. The only solution seems to be to restart Emacs by force-quitting it.
The author of Alchemist seems to think this is caused by an incompatibility between company quickhelp and the asynchronous way Alchemist returns documentation.

**Comment by expez** [comment]
Thanks for letting me know and creating an issue for others experiencing this problem to find.

However, if the Company backend is inefficient there's unfortunately nothing I can do.  All this mode does is request that information and display it in a popup.

**Comment by tonini** [comment]
Hi,

The problem is that Alchemist works async with with Alchemist-Server in the background. So we're using filters for our completion process request to the server in which we continues with the proper delivery to `company-mode`. So I guess quickhelp itself don't handle these kind of async processes at all and just expects the infos directly after it requests for the documentation. 

@houli I recommend setting `company-quickhelp-delay` to nil when you're in an `alchemist-mode`.

**Comment by expez** [comment]
> The problem is that Alchemist works async with with Alchemist-Server in the background.

This is not the problem.  The CIDER backend (for Clojure development) is also something company talks to asynchronously and that works just fine.

> So I guess quickhelp itself don't handle these kind of async processes at all and just expects the infos directly after it requests for the documentation.

All I do here is ask company for the doc string and then display it in a popup.

**Comment by tonini** [comment]
> This is not the problem. The CIDER backend (for Clojure development) is also something company talks to asynchronously and that works just fine.

This is actually great to hear, so I guess I'll have a look at the CIDER documentation backend first.

> All I do here is ask company for the doc string and then display it in a popup.

Damn, so you're on the easy side and I do something wrong ;-)

**Comment by tonini** [comment]
Ok, after testing it by myself I can't any issues or reproduce it. It works really nice for me.

So we need some help from @houli about this one, maybe he can reproduce it and have a look at the error outputs.

I guess the best place to talk about this in on the Alchemist repository itself, it's not company-quickhelps issue at all.

Thanks @expez

**Comment by tonini** [comment]
@houli Please open an issue on the Alchemist repository were we could talk about this issue.
