### ISSUE TITLE
Magit commits broken by company-quickhelp

### ISSUE THREAD

**Issue by 0x6d6e647a** [expez/company-quickhelp#34]
When committing using Magit ("c c" from Magit main buffer), an error occurs and then commit message buffer appears. However, when the commit message is submitted ("C-c C-c" from Magit commit message buffer), nothing actually happens.

Here is the error:

> `*ERROR*: Company: frontend company-quickhelp-frontend error "Symbol's function definition is void: pos-tip-hide" on command hide`

If I disable company-quickhelp the error goes away.

**Comment by expez** [comment]
`M-x toggle-debug-on-error <RET>`

You're going to be on your own here as I can't reproduce this.  I use both of these packages daily and I've no problems with the workflow you describe.

**Comment by 0x6d6e647a** [comment]
Here is a trace that occurs when I try to commit in the Magit main buffer:

> `Debugger entered--Lisp error: (void-function pos-tip-hide)`
> `pos-tip-hide()`
> `company-quickhelp-frontend(hide)`
> `#[0 "\301\300!\207" [hide company-quickhelp-frontend] 2 "\n\n(fn)"]()`
> `funcall(#[0 "\301\300!\207" [hide company-quickhelp-frontend] 2 "\n\n(fn)"])`
> `company-call-frontends(hide)`
> `company-cancel(abort)`
> `company-abort()`
> `company-post-command()`

When starting emacs I see the following in the Messages buffer:

> `Error in post-command-hook (company-post-command): (error "Company: frontend company-quickhelp-frontend error \"Symbol's function definition is void: pos-tip-hide\" on command hide")`

This is running Emacs v24.5.1 on Mac OS X 10.10.5. I upgraded all of my emacs packages before running this test.

**Comment by expez** [comment]
Do `M-x find-library <RET> pos-tip <RET>`

do you see this in that file?

``` el
(defalias 'pos-tip-hide 'x-hide-tip
  "Hide pos-tip's tooltip.")
```

If not, or perhaps anyway, you might try to put this in your `.emacs`:

`(defun pos-tip-hide () (x-hide-tip))`

Which is just a more verbose and inefficient variant of what the `defalias` does.
