### ISSUE TITLE
Line breaks are not being respected

### ISSUE THREAD

**Issue by nosami** [expez/company-quickhelp#35]
First of all, thanks for the great plugin! 

<img width="1166" alt="screen shot 2016-03-18 at 23 18 37" src="https://cloud.githubusercontent.com/assets/667194/13894504/4f7f3922-ed60-11e5-926a-495e9120fab9.png">

This screenshot is from emacs-fsharp-mode. It looks as if company-quickhelp doesn't respect line breaks that appear in the output.

I can understand the text wrapping, but I think that line breaks should be respected because it makes the popup quite difficult to read otherwise.

**Comment by nosami** [comment]
This is the text verbatim

```
member FSharpCheckFileResults.GetSymbolUseAtLocation : line:int * colAtEndOfNames:int * lineText:string * names:string list -> Async<FSharpSymbolUse option>","Comment":"Resolve the names at the given location to a use of symbol.\n\ncolAtEndOfNames: The column number at the end of the identifiers where the information is being requested.\nline: The line number where the information is being requested.\nlineText: The text of the line where the information is being requested.\nnames: The identifiers at the location where the information is being requested.
```

**Comment by expez** [comment]
All I do is display the text provided by `company` in a popup.  Lines are indeed wrapped to limit the size of the popup, but I'm not messing with any newlines.

I'm guessing the text looks like this in the popup buffer you get when you hit <kbd>f1</kbd> on a completion candidate provided by company?  

If that's the case then the problem is most likely with the company backend in emacs-fsharp-mode.

**Comment by nosami** [comment]
The text at the bottom of my screenshot is the result of me pressing F1. You can see that there are more line breaks there.

**Comment by nosami** [comment]
It looks as if only the double `\n\n` has been preserved.

**Comment by expez** [comment]
It seems `pos-tip-fill-string` is the offender.  This is the library company-quickhelp uses to create the documentation popup.

If you want to get your hands dirty you you can open an issue / PR over [here](https://github.com/pitkali/pos-tip).  pos-tip has been deemed finished (and/or abandoned) by its original creator but this is the place to submit PRs.

**Comment by nosami** [comment]
Ok. Thanks!
