### ISSUE TITLE
How to customize faces?

### ISSUE THREAD

**Issue by otrenav** [expez/company-quickhelp#36]
I've tried using `M-x customize-group RET company-quickhelp RET` to find out how to customize faces. I've done the same with `pos-tip`, and followed [this advice](https://github.com/nashamri/spacemacs-theme/issues/11). However, I'm still unable to change the faces.

Any hints on what may be happening?

Thanks for this great package!

**Comment by expez** [comment]
If you do 

``` el
(setq pos-tip-foreground-color "#abcde"
      pos-tip-background-color "#edcba")
```

It should just work.

My theme (solarized) seems to handle this for me, so I don't actually use these settings myself.

The difference might be in the engine producing the tooltip itself.  Do you know if it's GTK , Qt or something else?

**Comment by otrenav** [comment]
Thanks. You're right. In Linux what you suggested works fine. In Mac however, it doesn't. Probably because of the engine used. ¿Any suggestions about making it work in Mac? Thanks.

**Comment by expez** [comment]
> Any suggestions about making it work in Mac? 

I'd try an emacs built against Cocoa.

**Comment by otrenav** [comment]
Ok, thanks!

**Comment by domtronn** [comment]
Hi, sorry for bringing this up again, I read the advice here - But I'm still getting the native tooltips when using any `pos-tip` package on Cocoa Emacs 25.1 on Mac OS X 10.11.

Were people able to get this to work on MacOS?

**Comment by domtronn** [comment]
<img width="902" alt="screen shot 2017-04-08 at 08 43 36" src="https://cloud.githubusercontent.com/assets/5881414/24826874/a94db90e-1c37-11e7-9342-8ee627dd5b05.png">

Here's a screenshot of some of the things I've tried, including settings the `pos-tip-foreground` and `pos-tip-background` variables to different colours. Interestingly, the last `x-show-tip` call obeys the positional `left` and `top` parts of the frame parameters, but just not the `foreground-color` 😞

**Comment by expez** [comment]
I've no idea, sorry.  Currently don't have access to a mac.

**Comment by otrenav** [comment]
@domtronn I tried it on Mac again, and I'm having the same problem as you are (in Ubuntu it works fine). I'll just leave it as it is since it's not critical for me. Best of luck.

**Comment by abbaswasim** [comment]
@domtronn did you ended up solving the issue on Mac or gave up?

**Comment by dgutov** [comment]
If the problem on Mac persists in the latest versions of Emacs, and the `tooltip` faces customizations are not honored, it might be worth a bug report.
