### ISSUE TITLE
buffer autoclose on windmove after using company-quickhelp

### ISSUE THREAD

**Issue by 11111000000** [expez/company-quickhelp#37]
1. M-x company-quickhelp-mode
2. C-x 3
3. use some company & quickhelp
4. switch to second buffer and first one are closed automatically

**Comment by expez** [comment]
Can't reproduce.  I use both of these packages 8 hours a day.  If this was a problem in general I, and other users, would've noticed.  Is perhaps one of the buffers shown in the split view the `*help*` buffer?
