### ISSUE TITLE
problem in elixir-mode

### ISSUE THREAD

**Issue by ngnguyen1** [expez/company-quickhelp#38]
I got the problem in elixir-mode.
Example: I type: `Map.` then a list candidates but i can't select any of them. This problem is only occurred in elixir mode. I also tried in emacs-lisp-mode then it works fine.  Can you help me to fix that?

**Comment by expez** [comment]
@tonini any ideas?

**Comment by expez** [comment]
Did you figure it out @NgaNguyenDuy?  

I've no idea what's causing your troubles.  You might have better luck opening an issue over at either company mode or at the elixir mode repo.  company is the package responsible for created the overlays of completion candidates, and letting you move among them, but it relies on elixir mode to provide the candidates and the documentation for those candidates.
