### ISSUE TITLE
quickhelp popup position overlap with candidates

### ISSUE THREAD

**Issue by futurist** [expez/company-quickhelp#39]
Sometimes the quickhelp popup position overlap with candidates, and maybe shifted when move between candidates. (OSX 10.9.5 + Emacs 24.5)

![2016-04-20 7 23 00](https://cloud.githubusercontent.com/assets/159167/14658780/13e4c18e-06c9-11e6-99fd-e42ebbf6e75f.png)

**Comment by futurist** [comment]
also tested in windows xp+32bit, emacs 24.5,

![1234](https://cloud.githubusercontent.com/assets/159167/14660078/44abdd88-06d4-11e6-9866-4ac4b6d40ebd.jpg)

![1234](https://cloud.githubusercontent.com/assets/159167/14661424/1e55b1d4-06e0-11e6-9055-479deed333ae.jpg)

**Comment by expez** [comment]
Without some reliable way of reproducing this there's nothing I can do.  It works on my computer :(

The library is tiny so you might get some insight into what's going wrong yourself, by stepping through the source using edebug.

**Comment by seanfarley** [comment]
This is fairly easy to reproduce for me: just make the buffer narrow enough such that the candidate list + quickhelp pop would go past the edge of the buffer. That always puts the quickhelp popup over the candidate list..
