### ISSUE TITLE
Help popup goes blank momentarily after initial display

### ISSUE THREAD

**Issue by asampal** [expez/company-quickhelp#40]
I'm using Emacs 24.5.1 on Windows 10 64 bit, with the latest packages from Melpa as of 4/22/2016.

After quickhelp pops up initially for a symbol, it blanks out for a fraction of a second and then re-displays the content. Is this a known issue or is there some parameter that could be causing this?

![popup-flash](https://cloud.githubusercontent.com/assets/281639/14752235/21441936-089c-11e6-9a70-a3a5267095f5.gif)

**Comment by expez** [comment]
This might be related to the underlying display engine.  Does this blinking happen if you evaluate `(pos-tip-show "this")` manually?

**Comment by asampal** [comment]
It doesn't happen when I evaluate `pos-tip-show`. In fact, when I use Cider with Clojure, there are tooltips on hover and those display without the flash.

**Comment by expez** [comment]
Are you by any chance using <kbd>M-h</kbd> to manually trigger the popup?

**Comment by asampal** [comment]
No, the help is set to automatically pop up.

**Comment by expez** [comment]
Then I am stumped.  I've no more theories as to why this is happening.  My only other suggestion is for you to step through `company-quickhelp--show` in [edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html) to see where it's at when the blink happens.

**Comment by asampal** [comment]
I've noticed the following. Let's say I'm in the `*scratch*` buffer.
- I type `(def`
- The auto-completion popup appears and in the minibuffer the text `Type "q" in help window to restore its previous buffer.` is shown. The quickhelp popup also appears at this time despite `company-quickhelp-delay` being set to 0.5. 
- The previous line is replaced in the minibuffer with the first line of the documentation for the symbol at point. The display of this line seems to coincide with the blanking of the quickhelp popup and so appears for only a fraction of a second.
- The text `Type "q" in help window to restore its previous buffer.` reappears in the minibuffer at the same time as the documentation reappears in the quickhelp popup.

It seems that sometimes company-quickhelp doesn't obey the initial delay for some reason and in those instances you get the flashing. Sometimes the flashing doesn't occur and the quickhelp popup appears after the brief delay that is set.

**Comment by asampal** [comment]
Does company-quickhelp attempt to also display help in the minibuffer? I've disabled eldoc mode so that shouldn't be it.

**Comment by expez** [comment]
This is the flow of things:
1. The candidate list appears
2. After you've moved onto a candidate we set a timer and save it in `company-quickhelp--timer`
3. The timer expires after `company-quickhelp-delay` seconds
4. `company-quickhelp--show` now runs
5. We cancel the timer in `company-quickhelp--timer` (in case another popup request was made in the interim)
6. We ask company what the currently selected candidate is
7. The doc is retrieved from the help buffer (what this is depends on the company backend.  For elisp it is the `*help*` buffer but for clojure, with CIDER, it is `*cider-help*`)
8. The documentation is displayed in a popup using `popup.el`

> Does company-quickhelp attempt to also display help in the minibuffer

No

**Comment by asampal** [comment]
So there is no way that the quickhelp popup could unintentionally be shown as soon as the auto-completion popup is shown instead of after the delay?

**Comment by expez** [comment]
> So there is no way that the quickhelp popup could unintentionally be shown as soon as the auto-completion popup is shown instead of after the delay?

I've been writing software for too long to use terms like 'no way' :p  But through inspection it's hard to see what might be going wrong.  

I think you'd get an answer relatively quickly if you instrument either company-quickhelp or pos-tip (the library creating the popup) using edebug.  If you haven't used it before, learning enough edebug to make this happen will be well worth your time.  It should only take 5 minutes with the manual I linked above, and it will give you the powers to understand anything weird emacs is doing going forward.

I'm sorry I can't help you in a more direct manner.  Most of the issues opened against this library unfortunately end with "I can't reproduce this, you're going to have to investigate yourself" which I realize is a very frustrating response to get as a consumer of an emacs package.

**Comment by asampal** [comment]
OK, I'll give the debugging a try after I get some sleep. The only problem I see is that trying to debug timer related issues (which I'm assuming imply multiple threads) with a debugger is kind of a pain because of the changed conditions you have when paused in one thread in the debugger vs what you'd see in regular execution.

**Comment by expez** [comment]
Emacs is single-thread so it's relatively straight forward :)
