### ISSUE TITLE
feature request: toggle pos-tip on and off

### ISSUE THREAD

**Issue by nverno** [expez/company-quickhelp#41]
Would it be worth adding a toggle on/off function?  I was using the following because the overlay was blocking the dropdown on occasion

```

(defun company-quickhelp-toggle ()
  "Toggle pos-tip on and off."
  (interactive)
  (or (x-hide-tip)
      (company-quickhelp-manual-begin)))
(define-key company-quickhelp-mode-map (kbd "M-h")
  #'company-quickhelp-toggle)

```

**Comment by expez** [comment]
I don't think so, personally, as the popup disappears as soon as you interact with the list of candidates (e.g. move between candidates) but I don't think it'll do any harm either.  I'll accept a PR, in the hope that someone else finds it useful too, if you want to move your changes upstream :)

**Comment by nverno** [comment]
Yes, it's not a very perfect toggle function I'm afraid.  I like it when I only rarely want to see the docs in the popup, but I think a better lisp programmer would improve it for other cases.  Feel free to close the issue (or should I?  I'm not really sure of the edicate with respect to these matters).

**Comment by didibus** [comment]
I think something like this should be revisited, as it seems when doc is really big, it hides the drop down list, which makes it hard to see. Also, some buffers (Cider REPL buffer) doesn't seem to close the popup when using manual-begin, so pressing M-h again just re-opens it.

**Comment by nverno** [comment]
I've been having this problem for a while as well.  Have you been able to pinpoint the problem location?  Is it caused on company's end in the pre/post-command-hooks?  Cause those could be temporarily disabled.

**Comment by didibus** [comment]
I havn't been able to no. I tried some things, and it wasn't working as well as it needed too, so I just disabled company-quickhelp and use C-h instead of M-h.

**Comment by nverno** [comment]
@didibus I eventually got around to fixing it.  The following works - the problem is somewhere in the proper cancelling of the timer, although I'm not entirely sure what is happening anymore (I think I had it figured out when I wrote this but, now looking back at it I'm confused why the second version bugs out on rapid repitition).  The first version is superior and seems to work fine.  The second is a bit buggy -- if you repeatedly toggle very quickly (faster than the `company-quickhelp-delay` I believe, but haven't actually tried to debug it), the popup seems to stop working until moving to another candidate.

```
(defun my-company-quickhelp-toggle-1 ()
  "Toggle pos-tip help on/off."
  (interactive)
  ;; tell `company-quickhelp--manual-begin' to start the timer
  ;; alternatively, cancel `company-quickhelp--cancel-timer'
  (if (not (eq this-command last-command))
      (company-quickhelp-manual-begin)
    (x-hide-tip)
    (setq this-command 'company-quickhelp-manual-begin)))

(defun my-company-quickhelp-toggle-2 ()
  (interactive)
  (if (not (eq this-command last-command))
      (company-quickhelp-manual-begin)
    (x-hide-tip)
    (company-quickhelp--cancel-timer)))

```
