### ISSUE TITLE
Doesn't work on Non-GUI system

### ISSUE THREAD

**Issue by seagle0128** [expez/company-quickhelp#46]
It seems pos-tip only supports GUI system. Do you have any plan to support Non-GUI system, or move it to popup which supports both systems?  Thanks!

**Comment by expez** [comment]
No, I only use GUI myself and I unfortunately have to prioritize my time as of late.  

Furthermore, the only non-GUI popup lib I'm aware of is `popup.el` which is so buggy it was one of the prime motivators for me when switching from autocomplete to company.

Hopefully someone else will make something which fulfills your needs at some point.  If not, you could always roll up your sleeves and hack on emacs yourself :)

**Comment by seagle0128** [comment]
It seems there is no solution so far and have to make it myself.
Thanks, anyway.

**Comment by articuluxe** [comment]
@seagle0128 Did you end up coming up with anything?
