### ISSUE TITLE
quickhelp "freezes" emacs when using alchemist package

### ISSUE THREAD

**Issue by Trevoke** [expez/company-quickhelp#47]
With the delay set to 0.5, emacs became almost unresponsive, I had to hit `C-g` a bunch and wait and hope.

This is with emacs 25 (railwaymacs port) on OSX, trying company-quickhelp on an Elixir buffer (using the alchemist package).

Quickhelp works quite well in an elisp buffer.

This issue is known in alchemist: https://github.com/tonini/alchemist.el/issues/210

**Comment by expez** [comment]
I think the company backend for Elixir, in the alchemist package, has some flaws.  I keep getting issues opened against this repo when people use that package.

Are you seeing this issue in any other buffers, e.g. emacs lisp buffers?  If not, I think you should open an issue against the alchemist repo.

**Comment by Trevoke** [comment]
Ah, good point! It works really well in emacs-lisp. Maybe we can leave this issue open so others will stop opening the issue? I'll rename it to mark that the problem is only with alchemist, open an issue on alchemist, then link it here for others?

**Comment by expez** [comment]
> Maybe we can leave this issue open so others will stop opening the issue?

I prefer issues to be actionable (on my part), so I'll close this.  Users who use google will find several issues related to company-quickhelp and elixir/alchemist, so I'm not that worried about discovery.

**Comment by Trevoke** [comment]
You say this and yet you also said "people keep on opening issues about
this" :D

**Comment by Trevoke** [comment]
The alchemist company fix is out.
