### ISSUE TITLE
how to customize the tip font?

### ISSUE THREAD

**Issue by timepp** [expez/company-quickhelp#50]
Hi, thanks for this package. 

the font of the tip shown on my machine is not like other part of emacs (which is manoco). do you know how to change it?

**Comment by expez** [comment]
Usually this is the job of the theme you're using, so you might want to open an issue / submit a PR over there. 

The vars to fiddle with are: 

``` el
(defvar pos-tip-foreground-color "#839496"
  "Default foreground color of pos-tip's tooltip.")

(defvar pos-tip-background-color "#073642"
  "Default background color of pos-tip's tooltip.")
```

defined in `pos-tip.el`.  Pos-tip is the library company-quickhelp uses to create the documentation popups.
