### ISSUE TITLE
[Question] Can I open quickhelp in a new buffer?

### ISSUE THREAD

**Issue by caisah** [expez/company-quickhelp#51]
I just started using `company-quickhelp` and I love it. But I was wondering if it's possible to open it in a new buffer, _helm style_, instead of using `pos-tip`.

Thanks!

**Comment by expez** [comment]
Anything is possible with emacs, but you'd have to hack that out yourself.  Just replace the call to `pos-tip` with something that creates a new buffer in an acceptable manner.  I don't use helm myself, but perhaps there is something you can hook into easily.
