### ISSUE TITLE
Allow for custom text colors

### ISSUE THREAD

**Issue by Pireax** [expez/company-quickhelp#53]
Hello,
I think it would be nice to be able to color certain elements in the text just like syntax highlighting. this would be possible with 'pos-tip-show-no-propertize' instead of 'pos-tip-show'. Let me know what you think.

**Comment by expez** [comment]
I can no longer recall why I picked one over the other. If you've done some digging, what at the differences?  Any reason not to switch?

**Comment by Pireax** [comment]
What I could find out is that calling 'pos-tip-show' will treat the text as just text without properties and apply the foreground color to all text. 'pos-tip-show-no-propertize' allows for the text to have properties which it won't override.

**Comment by expez** [comment]
I think if we implement this we should introduce a variable to toggle between them, just in case some backend returns text with ugly properties.

I'd love a PR, you want to get your hands dirty? :)

**Comment by Pireax** [comment]
Sure, i'll try it out and see what it does.
