### ISSUE TITLE
Screen flicker with daemon on initial startup

### ISSUE THREAD

**Issue by eflanigan00** [expez/company-quickhelp#55]
Emacs 25.1.1 on redhat 6.6
When I first open the window I get a flicker when the postips show up.
The redraw is not acting correctly.
I can immediately correct this by resizing the frame with my mouse. Then the flicker goes away.

This only happens in daemon mode (when I run 'emacs' I don't see the issue).

**Comment by expez** [comment]
I've no idea what to do about that.  You'd have to open an issue with someone further down the stack, involved in actually drawing the popups.  Either over at the `pos-tip` repo, with emacs itself or maybe even below that again.
