### ISSUE TITLE
the popup dialogue appears in random places

### ISSUE THREAD

**Issue by oracleyue** [expez/company-quickhelp#61]
Here is the situation: the popup dialogue of doc info is not besides the candidate list, but appears quite randomly, as shown below. (sometime, quite less frequently, it works well.) The worst case is like the last picture. It is my first time use `company-quickhelp`. Any ideas? Many thanks!

Configurations:
```
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(company-quickhelp-mode 1)
```

Versions:
- `company-20170112.200`   (the stable version on ELPA is the same)
- `company-quickhelp-20170119.2217`
- `emacs-25.1.91.1`
- `pos-tip-20150318.813`

<img width="704" alt="screen shot 2017-01-23 at 14 29 32" src="https://cloud.githubusercontent.com/assets/5046605/22206222/af46d220-e17a-11e6-8706-bc1995622101.png">
<img width="648" alt="screen shot 2017-01-23 at 14 29 40" src="https://cloud.githubusercontent.com/assets/5046605/22206226/b1aab658-e17a-11e6-8d45-078cd5ba44f6.png">
<img width="638" alt="screen shot 2017-01-23 at 14 30 01" src="https://cloud.githubusercontent.com/assets/5046605/22206234/b4be0660-e17a-11e6-853f-a2f7b9b202e1.png">
<img width="671" alt="screen shot 2017-01-23 at 14 30 14" src="https://cloud.githubusercontent.com/assets/5046605/22206235/b69c969a-e17a-11e6-9fe9-f0b813e4d5c8.png">
<img width="927" alt="screen shot 2017-01-23 at 14 30 25" src="https://cloud.githubusercontent.com/assets/5046605/22206236/b857acfe-e17a-11e6-8f85-ddecc0b82cfc.png">
<img width="750" alt="screen shot 2017-01-23 at 14 36 59" src="https://cloud.githubusercontent.com/assets/5046605/22206238/ba4a1812-e17a-11e6-8b45-8dea0fc710a2.png">

**Comment by expez** [comment]
There's nothing I can do about this, unfortunately.  All I do is ask `pos-tip` to place the popup next to the list of candidates.  If `pos-tip` reckons it can't do that, then you get the unpleasing result in your screenshots :(

I too see this every once in a while, but it happens rarely, and I've not found any common thread that might be causing `pos-tip` to spazz out.

**Comment by oracleyue** [comment]
@expez Oh, okay, so it's actually a `pos-tip`'s bug. So in your case, such issue only happens rarely? Unfortunately, it happens almost surely in mime. Let's wait for `pos-tip` updates.

**Comment by expez** [comment]
I get it consistently when my cursor is at the edge of the window (typically this is at the edge of the screen too for me), but that's to be expected because there's no room next to the candidates to place the popup...

**Comment by oracleyue** [comment]
@expez All right. Then there must be certain problems in my setup, maybe conflicts between other packages? Let me test later, and I will update here. Thanks all the same!
