### ISSUE TITLE
company-quickhelp doesn't work in terminal

### ISSUE THREAD

**Issue by naclander** [expez/company-quickhelp#62]
I'm running emacs in terminal mode ( `-nw` ), version `24.5.1`.

I noticed this really cool plugin and wanted to try it out. Unfortunately, when running `company-quickhelp-manual-begin` manually, I noticed the error:

    Error running timer `company-quickhelp--show': 
    (user-error "Company-quickhelp doesn't work in the terminal")

Please make this plugin work with emacs terminal mode.

**Comment by naclander** [comment]
I just noticed https://github.com/expez/company-quickhelp/issues/24

Can you please add to the README saying that terminal mode is not supported?

**Comment by expez** [comment]
Sure

**Comment by wusticality** [comment]
Is supporting this package for the terminal overly complicated? I sure wish it worked ..

**Comment by expez** [comment]
> Is supporting this package for the terminal overly complicated?

No, it's not hard.  Just replace `pos-tip` with `popup` and make a few tweaks here and there.  Be warned that `popup` is pretty buggy, though.

If you want to maintain such a fork I'd be super happy to link to it for everyone that comes here and is disappointed by my lack of support for the terminal.

**Comment by wusticality** [comment]
I'll have to think on that, I'm got a big move ahead of me so things are a bit crazy.

I think `auto-complete` uses `popup.el` too actually ..

**Comment by ahungry** [comment]
https://github.com/ahungry/company-quickhelp has TTY support in my fork now
