### ISSUE TITLE
Unable to define-key in company-active-map

### ISSUE THREAD

**Issue by naclander** [expez/company-quickhelp#63]
After enabling company-quickhelp with

```elisp
(company-quickhelp-mode 1)
```
The keybindings I set up in company-active-map don't seem to hold anymore. Specifically:

```elisp
(define-key company-active-map (kbd "C-n") 'company-select-next-or-abort)
(define-key company-active-map (kbd "C-p") 'company-select-previous-or-abort)
```
Is this intended behavior? If so, do you know of a way around this issue?

**Comment by expez** [comment]
I don't know why this is happening to you.  I have the following, in my `.emacs`,

```el
(fill-keymap company-active-map
             "C-l" 'company-complete-common
             "C-k" 'company-complete-selection
             (kbd "TAB") 'yas-expand)
```

and it works fine.

**Comment by naclander** [comment]
I'm not familiar with `fill-keymap`, what does it do?

When `company-quickhelp-mode` is deactivated, the mapping works fine, so I am assuming this is some issue with quickhelp.

**Comment by expez** [comment]
> I'm not familiar with fill-keymap, what does it do?

It's an abstraction living in my `.emacs`, but in this case all it does is make the appropriate calls to `define-key`, like in the example code you pasted above.

> When company-quickhelp-mode is deactivated, the mapping works fine, so I am assuming this is some issue with quickhelp.

Reasonable assumption, but I can't reproduce.

If you set `company-quickhelp-delay` to some high value, like say 10 sec, are the keybindings working up to the point where company quickhelp comes to life?  Or is it enough to just activate the mode?

**Comment by naclander** [comment]
I added 
```elisp
(setq company-quickhelp-delay 10)
``` 
And like you said, the bindings work up until 10 seconds later, when the tooltip kicks in. 

Are you saying you cannot reproduce this when you change your `fill-keymap` function directly to `define-key`?

**Comment by expez** [comment]
> And like you said, the bindings work up until 10 seconds later, when the tooltip kicks in.

Aight, then what happens is that `company-active-map` stops being active when `company-quickhelp` creates a popup.  Looking at the code in `company` this can happen if there's an error during its operation.  Each such error is logged to the `*messages*` buffer.  Do you see any error messages from company in that buffer?

> Are you saying you cannot reproduce this when you change your fill-keymap function directly to define-key?

Yes

**Comment by naclander** [comment]
I started typing something, waited for the tooltip to pop up, and then I started trying to iterate through the company-mode options using the `"C-n" "C-p"` mappings I had above. I see the following in the messsages buffer:

```
Type "q" in help window to delete it.
Scanning for dabbrevs...done
Expansion found in ‘*Help*’
Scanning for dabbrevs...done
user-error: No dynamic expansion for ‘company--electric-saved-window-configuration’ found
Scanning for dabbrevs...done
user-error: No dynamic expansion for ‘company--electric-saved-window-configuration’ found
Scanning for dabbrevs...done
user-error: No dynamic expansion for ‘company--electric-saved-window-configuration’ found
```

The alternating messages happen depending on whether i press `"C-n"` or `"C-p"`. Also above, `company--electric-saved-window-configuration` was the option I was currently hovering over in company-mode. I'm not really sure what to make of these errors though.

**Comment by expez** [comment]
Aight, then this doesn't have anything to do with company-quickhelp.    If you fix the errors (wherever they're coming from) you'll get the behavior you want.

**Comment by twlz0ne** [comment]
Same issue here, and no error in `*Messages*` buffer.

The `C-n` and `C-p` works until `quickhelp` appears. But only occurs in `emacs-lisp` mode.

- macOS 10.11
- Emacs 25.2.1
- Quickhelp 1.4.0

**Comment by twlz0ne** [comment]
I found the problem. because i binded `C-n/p` to `evil-next/previous-visual-line` in `evil(inert state)`, there's a conflicat. my solution is:

```elisp
(add-hook
 'company-completion-started-hook
 (lambda (&rest ignore)
   (when evil-mode
     (when (evil-insert-state-p)
       (define-key evil-insert-state-map (kbd "C-n") nil)
       (define-key evil-insert-state-map (kbd "C-p") nil)
       ))))
```

But why only `emacs-lisp` has this problem？
