### ISSUE TITLE
Emacs 24.3 compatibility?

### ISSUE THREAD

**Issue by cpitclaudel** [expez/company-quickhelp#70]
I just noticed that company-quickhelp depends on Emacs-24.4.  Quick tests suggest that it builds just fine on 24.3, though the pop-up's position seems off.

Are there known issues with 24.3?  I'm asking because 24.3 still ships with Ubuntu LTS, so I'm hesitant to reject it for my own packages (but I'd like to depend on company-quickhelp)

**Comment by expez** [comment]
I just didn't want to commit to supporting 24.3.  I've had reports of users using it successfully on that version, though.

**Comment by cpitclaudel** [comment]
Makes sense.  There's no way to register soft dependencies in ELPA, right? (As in, I can't say to package.el "install this if available, but don't fail otherwise", correct?)

**Comment by expez** [comment]
I'm cool with adding support for 24.3, but I don't have time to spend on issues specific to that version.

Do you want commit rights to shoulder that burden? :)

**Comment by cpitclaudel** [comment]
I'm in :)

**Comment by cpitclaudel** [comment]
Permission for my first push to be the one that changes the version number of our Emacs dependency ? :)

**Comment by expez** [comment]
Go for it! :+1:
