### ISSUE TITLE
Quickhelp tooltip gets positioned incorrectly when completion happens near the very end of the buffer

### ISSUE THREAD

**Issue by cpitclaudel** [expez/company-quickhelp#72]
This is likely to be what #52 was about, but that issue got a bit diluted.  Here's the repro.

- Start a fresh Emacs with company and company-quickhelp (I use MELPA's `make sandbox` for that)
- Open a new test.el file; turn on `company` and `company-quickhelp`
- Type `(defu`, then wait for completion to start and for a tooltip pop up to appear.

I see this:

![screenshot from 2017-04-20 21-00-51](https://cloud.githubusercontent.com/assets/8181630/25258323/78e933ae-260c-11e7-8ef4-d8d8d34462b7.png)

Adding two newlines after the defun fixes it:

![screenshot from 2017-04-20 21-01-34](https://cloud.githubusercontent.com/assets/8181630/25258341/8dfeba20-260c-11e7-88e4-45de1eae00fb.png)

**Comment by expez** [comment]
Yeah, I'm seeing the same, but I think this is a problem with pos-tip, or even the underlying display engine, which pos-tip in turn uses. 

I tested this on ubuntu.

**Comment by jcs090218** [comment]
Is there a solution for this issue, I encountered this issue on Windows 10...

**Comment by dgutov** [comment]
I think I've managed to track down this one.

Let me know if something is amiss.
