### ISSUE TITLE
quickhelp not always appearing for things with __doc__

### ISSUE THREAD

**Issue by ecbrown** [expez/company-quickhelp#73]
NB Wonderful tool, thank you very much.

I'm using emacs 26 (head) with elpy with current ipython and jedi, company (melpa) and company-quickhelp (melpa) on macOS 12.  However, there are circumstances for which no help appears, though I am certain that there is __doc__ available.  For example:
```
import random
random.betavariate  <---- no quickhelp
print(random.betavariate.__doc__)     <---- documentation present
```
but
```
random.Random    <---- gives quickhelp
```
Similarly,
```
[].append    <---- gives quick help
```
though hovering over:
```
[].pop     <---- does not give quick help
```

**Comment by ecbrown** [comment]
This may be a company problem, C-h on the candidate doesn't give any documentation.

**Comment by expez** [comment]
If <kbd>C-h</kbd> doesn't do any anything then there's nothing we can do (since we just display that result in a different way).  Most likely there's a problem with the backend for company, and not company itself.
