### ISSUE TITLE
not working on emacs 25.2.1?

### ISSUE THREAD

**Issue by CastixGitHub** [expez/company-quickhelp#74]
Hi there, I can get documentation from company pressing F1, but I want it into a popup, this is why I'm here :)

I'm using GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu)
```
company-quickhelp is an installed package.

     Status: Installed in ‘company-quickhelp-20170429.1052/’ (unsigned). [Delete]
    Version: 20170429.1052
    Summary: Popup documentation for completion candidates
   Requires: emacs-24.3, company-0.8.9, pos-tip-0.4.6
   Homepage: https://www.github.com/expez/company-quickhelp
   Keywords: [company] [popup] [documentation] [quickhelp]
Other versions: 20170429.1052 (melpa).
```
```
pos-tip is a dependency package.

     Status: Installed in ‘pos-tip-20150318.813/’ (unsigned).
    Version: 20150318.813
    Summary: Show tooltip at point
Required by: company-quickhelp-20170429.1052
   Keywords: [tooltip]
Other versions: 20150318.813 (melpa).
```

the popup does not appear :(
so I ran `M-x company-quickhelp-manual-begin` and I got an error, I enabled debug and I got the traceback
```
Debugger entered--Lisp error: (error "company-quickhelp is not available in this emacs version or frame")
  signal(error ("company-quickhelp is not available in this emacs version or frame"))
  error("company-quickhelp is not available in this emacs version or frame")
  company-quickhelp--show()
  apply(company-quickhelp--show nil)
  timer-event-handler([t 0 0 10000 nil company-quickhelp--show nil idle 0])
```
looking at the source...
```
(defun company-quickhelp--show ()
  (unless (company-quickhelp-pos-tip-available-p)
    (error "company-quickhelp is not available in this emacs version or frame"))
...
(defun company-quickhelp-pos-tip-available-p ()
  "Return t if and only if pos-tip is expected work in the current frame."
  (and
   (fboundp 'x-hide-tip)
   (fboundp 'x-show-tip)
   (not (memq window-system (list nil 'pc)))))
```
I don't get it :(
thanks :)

**Comment by cpitclaudel** [comment]
Thanks for all the details, and for investigating.  Can you show the value of `window-system` on your machine? Can you also check what `(fboundp 'x-hide-tip)` and `(fboundp 'x-show-tip)` return? This way we will see which part of the test fails.

Are you trying to use this package in a terminal frame, btw?

**Comment by CastixGitHub** [comment]
actually I'm new to emacs :)
both `fboundp` and even `windows-system` returns `nil` when evaluated from the scratch buffer with `C-x C-e`

I'm using emacs inside a urxvt terminal and I use i3wm as window manager.

**Comment by cpitclaudel** [comment]
Ah, this makes sense then. company-quickhelp only works on graphical frames.

**Comment by CastixGitHub** [comment]
Ouch :( 
I'm sorry

**Comment by cpitclaudel** [comment]
No problem at all. Sorry that we don't support terminal Emacs!
