### ISSUE TITLE
CIDER integration: docstring doesn't popup

### ISSUE THREAD

**Issue by vemv** [expez/company-quickhelp#75]
Hi again!

Just discovered this library. Looking great.

I cannot get it to work with cider though. Cider backend is in fact providing docstrings, as shown here:

![2017-11-01 13 08 06](https://user-images.githubusercontent.com/1162994/32274207-08de24f0-bf06-11e7-977e-8a983a3ca9e6.gif)

As I move through the completion popup, the CiderDoc buffer is updated accordingly. So cider <-> company integration seems correct.

(I opened CiderDoc window/buffer beforehand in this case)

Why could it be that company-quickhelp is not popping up?

These are my company-frontends:

`(company-pseudo-tooltip-unless-just-one-frontend company-echo-metadata-frontend company-preview-if-just-one-frontend company-quickhelp-frontend)`

---

Also I noticed something funny.

If I `(company-show-doc-buffer)` at a point apt for completion:

* normal comany popup will appear
* CiderDoc will automatically pop up for 1 second, then get auto-closed
* comany popup will remain, and I can use it normally.

Cheers - Victor

**Comment by expez** [comment]
What happens if you just hang out at one of the completion candidates for a little longer?

`company-quickhelp-delay` is set to 0.5 seconds by default, so you shouldn't expect to see any docs when you're just scrolling through the completion candidates like this.

**Comment by vemv** [comment]
Tried out, no luck!

**Comment by expez** [comment]
Are you in the terminal?  This only works in the GUI version of emacs.

**Comment by vemv** [comment]
GUI

**Comment by expez** [comment]
Unfortunately, I'm stumped.  

I'm not sure how familiar you are with Emacs, but the next step is to either use `edebug`, or debug prints, to find out what goes wrong.  The function to instrument is `company-quickhelp--show`.

**Comment by vemv** [comment]
Quite familiar, I debug things manually though ;p

Will try to debug. Btw, how can I be sure that pos-tip is actually being used (instead of popup-el)?

**Comment by expez** [comment]
popup-el isn't an option with company-quickhelp.

Are you running `auto-complete` at the same time?

**Comment by vemv** [comment]
Nope, auto-complete was nuked from my setup a year ago

> popup-el isn't an option with company-quickhelp.

This still doesn't prevent company-mode from using popup-el, and from not invoking company-quickhelp at all under some condition?

**Comment by expez** [comment]
Company doesn't use popup-el

**Comment by vemv** [comment]
Whoops that was noise, sorry for the confusion.

I'm looking at https://www.emacswiki.org/emacs/PosTip

![image](https://user-images.githubusercontent.com/1162994/32277854-1749f308-bf14-11e7-976e-edc4e6c2ce3a.png)

As per the emacswiki screenshot, looks like pos-tip uses some native stuff

I think pos-tip doesn't work at all in my emacs:

`(pos-tip-show "Hello" '("red"))`

...does nothing.

Using https://github.com/railwaycat/homebrew-emacsmacport

**Comment by expez** [comment]
Probably a problem with the native osx GUI in that port.  

Sadly that's nothing I can help you with :(

**Comment by vemv** [comment]
Indeed out to be an idiosyncrasy of https://github.com/railwaycat/homebrew-emacsmacport ; works fine with the more standard https://emacsformacosx.com/ . Pleasure to see it working (unstyled though)

![image](https://user-images.githubusercontent.com/1162994/32280156-3723024e-bf1b-11e7-9256-e98fe97cedff.png)

Sorry for the distracting issue!

I reckon you could add to the README a Troubleshooting section:

> Does pos-tip correctly work in your Emacs/OS combination? Try it with `(pos-tip-show "Hello" '("red"))`: a popup should appear.
