### ISSUE TITLE
How to load will be better?

### ISSUE THREAD

**Issue by yuzumx** [expez/company-quickhelp#76]
Hello:

I am a emacs rookie
Which of the following two ways is better?

environment: `company` and` company-quickhelp` are installed; Emacs 25.3.1.

1.
```emacs-lisp
(company-quickhelp-mode 1)
```

2.
```emacs-lisp
(with-eval-after-load 'company
  (company-quickhelp-mode 1))
```

I want to get an official answer, so I created this issue.
Sorry to be offended.

Thanks.

**Comment by cpitclaudel** [comment]
They are subtly different.  Both are equally OK, depending on what you want to achieve.  The first one loads company, whereas the second one doesn't.
Note that writing `(company-quickhelp-mode)` is enough; you don't need the `1`.

**Comment by yuzumx** [comment]
Thank you for your reply @cpitclaudel 
Well ... I found that they did not make any difference in loading speed ... because it was loaded anyway.

I added `1` because there is something written in your [README](https://github.com/expez/company-quickhelp#usage):
<img width="954" alt="2" src="https://user-images.githubusercontent.com/26828933/35309630-67769168-00e8-11e8-9cc6-053df6c329a8.png">


I have some obsessive-compulsive disorder, I'm sorry.

**Comment by cpitclaudel** [comment]
> Well ... I found that they did not make any difference in loading speed ... because it was loaded anyway.

Indeed, if you load company unconditionally somewhere else in your init file, then both forms are equivalent.

> I added 1 because there is something written in your README:

Thanks! Will fix.

> I have some obsessive-compulsive disorder, I'm sorry.

No apologies needed. Thanks for your message, and enjoy company-quickhelp!

**Comment by yuzumx** [comment]
Thanks you very much
