### ISSUE TITLE
Add an option for specifying extra function to get doc other than default `doc-buffer` backend call

### ISSUE THREAD

**Issue by stardiviner** [expez/company-quickhelp#77]
I try to implement an frontend like `company-quickhelp` called `company-quickdict` for `company-ispell`. It can popup dictionary result for selected candidate.
But after check out `company-quickhelp` source code, I give up on adopt code and create a new one package's idea. Thought why not let `company-quickhelp` support this kind of extra source doc function?
So here is my thought:
- Add an option like `company-quickhelp-backend-function` to get doc-buffer. In my case, I want to integrate sdcv.el https://github.com/stardiviner/sdcv.el . It has a function `sdcv-search-simple` can get back the dictionary result.
- Let `company-quickhelp--fetch-docstring` in `company-quickhelp--doc` decide whether the `company-backend` has doc-buffer, if not (like `company-ispell`), then use user specified function. In this place, I think use a `defcustom` /alist/ like `'((company-ispell . sdcv-search-simple) ..))` or similar, let user can specify backend call for a specific `company-backend`.

What do you think?

**Comment by cpitclaudel** [comment]
Hi there.
Wouldn't it be simpler to define a company-ispell-with-definitions backend that call company-ispell for all queries except `doc-buffer`?  Alternatively, you could also advise the company-ispell function.

**Comment by stardiviner** [comment]
Curious how to write advice for `company-ispell` ? Can you show me a simple code demo?

**Comment by stardiviner** [comment]
Here is my try:
```elisp
(defun company-ispell-dict (command &optional arg &rest ignored)
  "Provide dict as `doc-buffer' for `company-quickdict' popup."
  (interactive (list 'interactive))
  (cl-case command
    (doc-buffer
     (let ((doc (sdcv-search-simple arg)))
       (when doc
         (company-doc-buffer doc))))))

(advice-add 'company-ispell :after #'company-ispell-dict)
```
But seems wrong.

**Comment by cpitclaudel** [comment]
I think the non-advice version would be better; I'd do this:

```
(defun company-ispell-dict (command &optional arg &rest ignored)
  "Provide dict as `doc-buffer' for `company-quickdict' popup."
  (interactive (list 'interactive))
  (cl-case command
    (doc-buffer
     (let ((doc (sdcv-search-simple arg)))
       (when doc
         (company-doc-buffer doc))))
    (t (apply #'company-ispell command arg ignored))))
```

**Comment by stardiviner** [comment]
This works great. Thanks.
