### ISSUE TITLE
The quickhelp box doesn't disappear in emacs 27.0.50

### ISSUE THREAD

**Issue by eflanigan00** [expez/company-quickhelp#78]
After I scroll and see the help, I make a selection.
The company variable inserts into the buffer but hte quickhelp stays on the screen.
Not sure if this is a bug in this, postips, emacs or ubuntu.

**Comment by expez** [comment]
That doesn't sound good!

I don't have time to test emacs 27 on an ubuntu machine right now, but it's on my list.

**Comment by NightMachinery** [comment]
I can confirm that I don't have this issue with Emacs 27.0.50 on macOS. Further info:

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            crystal
            (haskell :variables haskell-enable-hindent t)
            html python chrome
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git
            (java :variables java-backend 'ensime)
            markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-tooltips t)
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by eflanigan00** [comment]
Not sure what corrected this but I'm no longer seeing the problem.
