### ISSUE TITLE
Bad times are had when completing java methods in cider-repl-mode 

### ISSUE THREAD

**Issue by expez** [expez/company-quickhelp#8]
This prompt below appears on every keystroke, to choose among the available candidates before grabbing documentation for our popup.

![.](http://i.imgur.com/cnD0o7h.png)

**Comment by expez** [comment]
I'd like to avoid doing something like this, @bbatsov:

``` elisp
(defun company-quickhelp--doc (selected)
  (cl-letf (((symbol-function 'cider--var-choice) (lambda (_) (error "Ambiguous candidate!"))))
    ...))
```

Could we perhaps introduce `*cider--tooling-context*` which tools can bind to `t` before calling into `CIDER`? In the case of the documentation buffer, an empty buffer, or one containing a short text stating that documentation isn't available before disambiguation would make sense.

**Comment by dgutov** [comment]
Maybe you can bind `completing-read-function` locally to one that just picks the first option?

**Comment by expez** [comment]
Yeah, that's a good idea, and more general than the hack I put in my `.emacs` while deliberating what to do about this.

My concern was that the popup would be misleading, and it would be better to fail gracefully and let the user know about the situation.  But the popup already is misleading, the annotations are all out of whack in these situations, and the user might prefer seeing documentation for one of the candidates rather than an entirely unhelpful message about ambiguity.

**Comment by bbatsov** [comment]
You can also merge all possible candidates I guess.

On 18 April 2015 at 10:01, Lars Andersen notifications@github.com wrote:

> Closed #8 https://github.com/expez/company-quickhelp/issues/8 via
> ef01c60
> https://github.com/expez/company-quickhelp/commit/ef01c6042a40fe31cf60ef8c01609e98fe2b2e62
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/expez/company-quickhelp/issues/8#event-284408476.

## 

Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by dgutov** [comment]
That might require some tricky inversion of control, though: then the amount of times this frontend would call `doc-buffer` would be dependent on how much (and if at all) `completing-read` was called during the first `doc-buffer` call. Should be doable, though.

Could also be slow for certain methods.

**Comment by expez** [comment]
Merge all candidates as in display all the docs?  java docstrings--at least those in the standard library--are often the length of novels so that's going to get out of hand real quick :)
