### ISSUE TITLE
Doesn't work with Emacs Mac Port

### ISSUE THREAD

**Issue by NightMachinery** [expez/company-quickhelp#80]
It seems pos-tip is not compatible with https://github.com/railwaycat/homebrew-emacsmacport . Enabling the quick help causes the completion popup to close when navigating completion candidates. This issue is not present in vanilla GNU emacs. (The tooltip there is small and ugly though. It'd be much better if it could be made bigger.)
PS: Have you seen https://github.com/tumashu/posframe ? Any hopes for using that instead of pos-tip?

**Comment by cpitclaudel** [comment]
> The tooltip there is small and ugly though. It'd be much better if it could be made bigger.

Check out x-gtk-use-system-tooltips, maybe

> PS: Have you seen https://github.com/tumashu/posframe ? Any hopes for using that instead of pos-tip?

Yes, I even contributed a draft implementation of it a while ago.  I don't think individual packages should switch to it; instead, you can overwrite pos-tip's entry points with posframe ones.

**Comment by expez** [comment]
Supporting custom builds of emacs is out of scope for this package.

Sorry!
