### ISSUE TITLE
Unable the change ugly tooltip face

### ISSUE THREAD

**Issue by stardiviner** [expez/company-quickhelp#85]
The tooltip face is ugly.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/378699/38774450-1e4ad05a-409c-11e8-8b5a-ee539fb8aeee.png)

I can't change it even I disable use gtk+ tooltip. and set face `tooltip` with `:family` to specify font.
Here is my config:
```elisp
(use-package pos-tip
  :ensure t
  :defer t
  :preface (setq x-gtk-use-system-tooltips nil)
  :config
  (setq pos-tip-border-width 1
        pos-tip-internal-border-width 2)
  (set-face-attribute 'tooltip nil
                      :family "Hack")
  )
```

**Comment by cpitclaudel** [comment]
Are you sure this is a company-quickhelp issue? What does it look like if you run `(run-with-idle-timer 0 nil (lambda () (tooltip-show "AAA")))`?

**Comment by stardiviner** [comment]
Same display.

**Comment by cpitclaudel** [comment]
Ok, then this isn't a company-quickhelp bug :/
