### ISSUE TITLE
quickhelp show nothing but a samll blank tips

### ISSUE THREAD

**Issue by algking** [expez/company-quickhelp#89]
![image](https://user-images.githubusercontent.com/1456351/40858734-e1b22292-6611-11e8-825b-b66cd829b5ca.png)

I wonder why the company-quickhelp shows nothing like this, only a small tips with no content.

emacs version: 26.1  emacs mac-port
company-version :20180510
company-quickhelp-version 20180525
op-system : MAC

**Comment by expez** [comment]
I don't know, sorry.

I'm closing this as wontfix, not because I'm a douchebag, but because this is for sure related to your use of mac-port.  These are all problematic IME.  I went through all of them, before giving up and abandoning the platform entirely.

**Comment by algking** [comment]
after update the emacs-mac to `railwaycat/emacsmacport/emacs-mac: stable emacs-26.1-z-mac-7.0, HEAD`
the company-quickhelp works again , hope this help others.
![image](https://user-images.githubusercontent.com/1456351/41011186-458089da-696e-11e8-8209-88cf80ad6fc2.png)
@expez

**Comment by expez** [comment]
Thanks for reporting back.  Glad you got it working @algking!

**Comment by algking** [comment]
I find out why company-quick-help won't work in the emacs-mac , if I eval (pos-tip-show  "msg") function first , then company-quick-help will work well. If not, then just a little blank area show.

It seems the problem is in pos-tip.
