### ISSUE TITLE
Quickhelp showing blank popups Emacs26.1

### ISSUE THREAD

**Issue by connorjsmith** [expez/company-quickhelp#90]
Relatively new to emacs debugging, so please let me know if there's anything I can do to help triage/debug this.

I'm using Emacs 26.1 on Ubuntu 16.04

![blank tip](https://user-images.githubusercontent.com/5892363/42177841-3a176918-7dfc-11e8-9dd5-cdad486be17b.png)

**Comment by expez** [comment]
Is there a doc for that function?  That is, does this happen always or does it erroneously pop up when there is no doc to show?

**Comment by srustamo** [comment]
Looks like the same issue here. The docstring is there in my case, can be seen with <kbd>C-c h</kbd> while in completion session, setup as described [here.](https://github.com/expez/company-quickhelp) Also note the weird size and position of the popup (marked with oval).

<img width="741" alt="screenshot 2018-07-03 21 50 26" src="https://user-images.githubusercontent.com/749813/42233745-d4bbfe88-7f0b-11e8-8ff4-1b87741809bd.png">

**Comment by connorjsmith** [comment]
Yeah the documentation is available via `f1` and `C-c h`. Popup doesn't occur when there is no documentation available (as expected). Also what's weird is the size of the popup changes as if it is sizing for longer/shorter docstrings, just no text appears.

**Comment by srustamo** [comment]
Played a bit with straight 'emacs-jedi' setup (without 'company-mode'), get a bit better result (see screenshot), fwiw.
<img width="969" alt="screenshot 2018-07-05 18 10 12" src="https://user-images.githubusercontent.com/749813/42325425-affb49a8-807f-11e8-8ec6-a2b65d7f16fa.png">

**Comment by Kaali** [comment]
The empty popup happens to me also. It fixes itself if I manually call `(pos-tip-show "foo")` once. Don't really know what the state problem is, but the bug is most probably in pos-tip itself.

**Comment by Kaali** [comment]
Seems to happen because pos-tip shows a temporary post-tip when calculating coordinates. Which happens after quickhelp shows it's pos-tip. When tracing `pos-tip-show` it's called twice when quickhelp activates, once with `pos-tip-show` and after that `pos-tip-show-no-propertize`. Which calls `pos-tip-show` with empty contents, and thus overrides the popup.

To disable this behavior you can set `pos-tip-use-relative-coordinates` to `t`. Which fixes the problem for me.

**Comment by expez** [comment]
Thanks for investigating and reporting back @Kaali! :+1:
