### ISSUE TITLE
company-quickhelp has trouble with ESS in an org-edit-special block 

### ISSUE THREAD

**Issue by kuwze** [expez/company-quickhelp#92]
When editing some R code in org-babel, and then switching context to just that source with org-edit-special (C-c '), company-quickhelp fails to load eldoc information. To reproduce this you would need to install R, enable R support in org-babel, and install ggplot2.

Here is a simple org-file that I am testing against:
```
#+BEGIN_SRC R :results output graphics :file test.png :width 800 :height 800  
library("ggplot2")
# type 'lm(' to start company (should start with 'model =', 'subset =', etc.) and wait to see if company-quickhelp pops up
ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species)) +
  geom_point()
#+END_SRC
```

**Comment by expez** [comment]
This is almost certainly not a problem with `company-quickhelp`.  Most likely `company` doesn't provide anything in this context, which is why the popup doesn't appear.

**Comment by kuwze** [comment]
Okay, sorry to bother you.
