### ISSUE TITLE
Company-clang and doc popups

### ISSUE THREAD

**Issue by ghost** [expez/company-quickhelp#93]
Hi there! I am new to your great tool. I am wondering if it is possible to get company-quickhelp to popup documentation tips for c/c++ code using company-clang? I've been searching for awhile now and I can't seem to get it to work, though it seems to be possible?

Any ideas?

**Comment by expez** [comment]
Most likely that backend for company doesn't provide docstrings.  If / when it does it should work automatically with `company-quickhelp`.

You can confirm this hypothesis by hitting <kbd>f1</kbd>, with a completion candidate selected, to trigger `company`s help buffer.  If no documentation is visible in the `**help**` buffer created by `company` then there's nothing for `company-quickhelp` to show and the failure is expected.
