### ISSUE TITLE
company-quickhelp position is incorrect with line numbers active

### ISSUE THREAD

**Issue by andreyorst** [expez/company-quickhelp#96]
`company-quickhelp` seem not to take into account width of line numbers: [[1]](https://user-images.githubusercontent.com/19470159/66599577-3950a700-ebac-11e9-8fc3-f033b9fda540.png), [[2]](https://user-images.githubusercontent.com/19470159/66599578-3950a700-ebac-11e9-9ca8-350b11b90dc1.png)

The issue looks similar to this one in `eldoc-box`: https://github.com/casouri/eldoc-box/issues/15#issuecomment-540518824

Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-10-09

**Comment by joca-bt** [comment]
I have the same issue, using Emacs line numbers package `(global-display-line-numbers-mode t)`.
