### ISSUE TITLE
text properties are ignored

### ISSUE THREAD

**Issue by andreyorst** [expez/company-quickhelp#98]
I've submitted this issue https://github.com/greghendershott/racket-mode/issues/405 to racket-mode repo and @greghendershott pointed out this thing:

> I was curious and spent an hour poking around. It looks like this is because [company-quickhelp uses `buffer-substring-no-properties`](https://github.com/expez/company-quickhelp/blob/master/company-quickhelp.el#L122) instead of `buffer-substring`. In other words it deliberately discards the properties.
> 
> If I change that to use `buffer-substring` -- _and_ also set `(setq company-quickhelp-use-propertized-text t)` -- then I do see the formatted text.

This actually prevents user from enabling propertized text.

**Comment by dgutov** [comment]
This should work now. Thanks for the report!

(You still need to change the value of `company-quickhelp-use-propertized-text` in your config).
